[package]
name = "app-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Application backend core"

[dependencies]
automerge-repo.workspace = true
async-trait.workspace = true
automerge.workspace = true
bytes.workspace = true
rusqlite.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
