// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_error`, `parse_collection`, `parse_draft_values`, `parse_field`, `parse_pending`, `parse_record`, `parse_records`, `parse_values`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`

Future<BootstrapDto> createNewDataset() =>
    RustLib.instance.api.crateApiCollectionsCreateNewDataset();

Future<String> createCollection({
  required String name,
  required String description,
}) => RustLib.instance.api.crateApiCollectionsCreateCollection(
  name: name,
  description: description,
);

Future<void> renameCollection({required String id, required String name}) =>
    RustLib.instance.api.crateApiCollectionsRenameCollection(
      id: id,
      name: name,
    );

/// Copies a collection's structure and views (no records); broken views are skipped and named.
Future<CloneOutcomeDto> cloneCollection({
  required String sourceId,
  required String name,
}) => RustLib.instance.api.crateApiCollectionsCloneCollection(
  sourceId: sourceId,
  name: name,
);

/// Active records of one collection as CSV text; the caller writes the file.
Future<String> exportCollectionCsv({required String id}) =>
    RustLib.instance.api.crateApiCollectionsExportCollectionCsv(id: id);

/// The given collections as one `fi-collection` JSON document.
Future<JsonExportDto> exportCollectionsJson({required List<String> ids}) =>
    RustLib.instance.api.crateApiCollectionsExportCollectionsJson(ids: ids);

/// Every active collection as one `fi-collection` JSON document.
Future<JsonExportDto> exportAllJson() =>
    RustLib.instance.api.crateApiCollectionsExportAllJson();

/// Adds every row of `text` as a new record; a rejected file writes nothing.
Future<ImportOutcomeDto> importCollectionCsv({
  required String collectionId,
  required String text,
}) => RustLib.instance.api.crateApiCollectionsImportCollectionCsv(
  collectionId: collectionId,
  text: text,
);

/// Creates new collections from a `fi-collection` document; a rejected document writes nothing.
Future<ImportOutcomeDto> importCollectionsJson({required String text}) =>
    RustLib.instance.api.crateApiCollectionsImportCollectionsJson(text: text);

Future<void> deleteCollection({required String id}) =>
    RustLib.instance.api.crateApiCollectionsDeleteCollection(id: id);

Future<List<CollectionDto>> listCollections() =>
    RustLib.instance.api.crateApiCollectionsListCollections();

Future<CollectionSchemaDto?> getCollectionSchema({required String id}) =>
    RustLib.instance.api.crateApiCollectionsGetCollectionSchema(id: id);

Future<String> addField({
  required String collectionId,
  required FieldDefinitionDto field,
}) => RustLib.instance.api.crateApiCollectionsAddField(
  collectionId: collectionId,
  field: field,
);

Future<void> updateField({
  required String collectionId,
  required FieldDefinitionDto field,
}) => RustLib.instance.api.crateApiCollectionsUpdateField(
  collectionId: collectionId,
  field: field,
);

Future<void> removeField({
  required String collectionId,
  required String fieldId,
}) => RustLib.instance.api.crateApiCollectionsRemoveField(
  collectionId: collectionId,
  fieldId: fieldId,
);

Future<void> reorderFields({
  required String collectionId,
  required List<String> fieldIds,
}) => RustLib.instance.api.crateApiCollectionsReorderFields(
  collectionId: collectionId,
  fieldIds: fieldIds,
);

Future<String> upsertEnumOption({
  required String collectionId,
  required String fieldId,
  required EnumOptionDto option,
}) => RustLib.instance.api.crateApiCollectionsUpsertEnumOption(
  collectionId: collectionId,
  fieldId: fieldId,
  option: option,
);

Future<void> removeEnumOption({
  required String collectionId,
  required String fieldId,
  required String optionId,
}) => RustLib.instance.api.crateApiCollectionsRemoveEnumOption(
  collectionId: collectionId,
  fieldId: fieldId,
  optionId: optionId,
);

Future<String> createRecord({
  required String collectionId,
  required List<RecordValueDto> values,
}) => RustLib.instance.api.crateApiCollectionsCreateRecord(
  collectionId: collectionId,
  values: values,
);

/// Dry-run record validation with create (no `record_id`) or merged-update
/// semantics. Returns every issue; empty when the draft is valid. Commits
/// nothing. Errs only for non-validation failures.
///
/// `pending_options` are options the form added; values pick them by key in place of an option
/// id, and their own problems are reported on their fields.
Future<List<BridgeIssueDto>> validateRecordDraft({
  required String collectionId,
  String? recordId,
  required List<RecordValueDto> values,
  required List<PendingOptionDto> pendingOptions,
}) => RustLib.instance.api.crateApiCollectionsValidateRecordDraft(
  collectionId: collectionId,
  recordId: recordId,
  values: values,
  pendingOptions: pendingOptions,
);

/// Saves a new record (no `record_id`) or the given changed fields of an existing one, together
/// with the options the form added, in one change. Returns the record id.
Future<String> saveRecordDraft({
  required String collectionId,
  String? recordId,
  required List<RecordValueDto> values,
  required List<PendingOptionDto> pendingOptions,
}) => RustLib.instance.api.crateApiCollectionsSaveRecordDraft(
  collectionId: collectionId,
  recordId: recordId,
  values: values,
  pendingOptions: pendingOptions,
);

/// Merges the `merge` options into `keep` on one Choice or Choices field.
Future<void> mergeEnumOptions({
  required String collectionId,
  required String fieldId,
  required String keep,
  required List<String> merge,
}) => RustLib.instance.api.crateApiCollectionsMergeEnumOptions(
  collectionId: collectionId,
  fieldId: fieldId,
  keep: keep,
  merge: merge,
);

Future<void> updateRecordField({
  required String recordId,
  required String collectionId,
  required String fieldId,
  required FieldValueDto value,
}) => RustLib.instance.api.crateApiCollectionsUpdateRecordField(
  recordId: recordId,
  collectionId: collectionId,
  fieldId: fieldId,
  value: value,
);

Future<void> deleteRecord({
  required String recordId,
  required String collectionId,
}) => RustLib.instance.api.crateApiCollectionsDeleteRecord(
  recordId: recordId,
  collectionId: collectionId,
);

Future<void> deleteRecords({
  required List<String> recordIds,
  required String collectionId,
}) => RustLib.instance.api.crateApiCollectionsDeleteRecords(
  recordIds: recordIds,
  collectionId: collectionId,
);

Future<List<String>> cloneRecords({
  required List<String> recordIds,
  required String collectionId,
}) => RustLib.instance.api.crateApiCollectionsCloneRecords(
  recordIds: recordIds,
  collectionId: collectionId,
);

Future<void> setRecordsField({
  required List<String> recordIds,
  required String collectionId,
  required String fieldId,
  required FieldValueDto value,
}) => RustLib.instance.api.crateApiCollectionsSetRecordsField(
  recordIds: recordIds,
  collectionId: collectionId,
  fieldId: fieldId,
  value: value,
);

Future<List<RecordDto>> listRecords({required String collectionId}) => RustLib
    .instance
    .api
    .crateApiCollectionsListRecords(collectionId: collectionId);

Future<RecordDto?> getRecord({required String id}) =>
    RustLib.instance.api.crateApiCollectionsGetRecord(id: id);

/// The new collection of a structure clone and the broken views that were not copied.
class CloneOutcomeDto {
  final String collectionId;
  final List<String> skippedViews;

  const CloneOutcomeDto({
    required this.collectionId,
    required this.skippedViews,
  });

  @override
  int get hashCode => collectionId.hashCode ^ skippedViews.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloneOutcomeDto &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          skippedViews == other.skippedViews;
}

/// A `fi-collection` document with what went into it; the caller writes the file.
class JsonExportDto {
  final String text;
  final int recordCount;
  final int viewsWritten;

  /// Names of the broken views left out.
  final List<String> viewsOmitted;

  const JsonExportDto({
    required this.text,
    required this.recordCount,
    required this.viewsWritten,
    required this.viewsOmitted,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      recordCount.hashCode ^
      viewsWritten.hashCode ^
      viewsOmitted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsonExportDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          recordCount == other.recordCount &&
          viewsWritten == other.viewsWritten &&
          viewsOmitted == other.viewsOmitted;
}
