// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_error`, `parse_collection`, `parse_field`, `parse_record`, `parse_records`, `parse_values`

Future<BootstrapDto> createNewDataset() =>
    RustLib.instance.api.crateApiCollectionsCreateNewDataset();

Future<String> createCollection({
  required String name,
  required String description,
}) => RustLib.instance.api.crateApiCollectionsCreateCollection(
  name: name,
  description: description,
);

Future<void> renameCollection({required String id, required String name}) =>
    RustLib.instance.api.crateApiCollectionsRenameCollection(
      id: id,
      name: name,
    );

/// Copies a collection's structure (no records) and returns the new collection id.
Future<String> cloneCollection({
  required String sourceId,
  required String name,
}) => RustLib.instance.api.crateApiCollectionsCloneCollection(
  sourceId: sourceId,
  name: name,
);

Future<void> deleteCollection({required String id}) =>
    RustLib.instance.api.crateApiCollectionsDeleteCollection(id: id);

Future<List<CollectionDto>> listCollections() =>
    RustLib.instance.api.crateApiCollectionsListCollections();

Future<CollectionSchemaDto?> getCollectionSchema({required String id}) =>
    RustLib.instance.api.crateApiCollectionsGetCollectionSchema(id: id);

Future<String> addField({
  required String collectionId,
  required FieldDefinitionDto field,
}) => RustLib.instance.api.crateApiCollectionsAddField(
  collectionId: collectionId,
  field: field,
);

Future<void> updateField({
  required String collectionId,
  required FieldDefinitionDto field,
}) => RustLib.instance.api.crateApiCollectionsUpdateField(
  collectionId: collectionId,
  field: field,
);

Future<void> removeField({
  required String collectionId,
  required String fieldId,
}) => RustLib.instance.api.crateApiCollectionsRemoveField(
  collectionId: collectionId,
  fieldId: fieldId,
);

Future<void> reorderFields({
  required String collectionId,
  required List<String> fieldIds,
}) => RustLib.instance.api.crateApiCollectionsReorderFields(
  collectionId: collectionId,
  fieldIds: fieldIds,
);

Future<String> upsertEnumOption({
  required String collectionId,
  required String fieldId,
  required EnumOptionDto option,
}) => RustLib.instance.api.crateApiCollectionsUpsertEnumOption(
  collectionId: collectionId,
  fieldId: fieldId,
  option: option,
);

Future<void> removeEnumOption({
  required String collectionId,
  required String fieldId,
  required String optionId,
}) => RustLib.instance.api.crateApiCollectionsRemoveEnumOption(
  collectionId: collectionId,
  fieldId: fieldId,
  optionId: optionId,
);

Future<String> createRecord({
  required String collectionId,
  required List<RecordValueDto> values,
}) => RustLib.instance.api.crateApiCollectionsCreateRecord(
  collectionId: collectionId,
  values: values,
);

/// Dry-run record validation with create (no `record_id`) or merged-update
/// semantics. Returns every issue; empty when the draft is valid. Commits
/// nothing. Errs only for non-validation failures.
Future<List<BridgeIssueDto>> validateRecordDraft({
  required String collectionId,
  String? recordId,
  required List<RecordValueDto> values,
}) => RustLib.instance.api.crateApiCollectionsValidateRecordDraft(
  collectionId: collectionId,
  recordId: recordId,
  values: values,
);

Future<void> updateRecordField({
  required String recordId,
  required String collectionId,
  required String fieldId,
  required FieldValueDto value,
}) => RustLib.instance.api.crateApiCollectionsUpdateRecordField(
  recordId: recordId,
  collectionId: collectionId,
  fieldId: fieldId,
  value: value,
);

Future<void> deleteRecord({
  required String recordId,
  required String collectionId,
}) => RustLib.instance.api.crateApiCollectionsDeleteRecord(
  recordId: recordId,
  collectionId: collectionId,
);

Future<void> deleteRecords({
  required List<String> recordIds,
  required String collectionId,
}) => RustLib.instance.api.crateApiCollectionsDeleteRecords(
  recordIds: recordIds,
  collectionId: collectionId,
);

Future<void> setRecordsField({
  required List<String> recordIds,
  required String collectionId,
  required String fieldId,
  required FieldValueDto value,
}) => RustLib.instance.api.crateApiCollectionsSetRecordsField(
  recordIds: recordIds,
  collectionId: collectionId,
  fieldId: fieldId,
  value: value,
);

Future<List<RecordDto>> listRecords({required String collectionId}) => RustLib
    .instance
    .api
    .crateApiCollectionsListRecords(collectionId: collectionId);

Future<RecordDto?> getRecord({required String id}) =>
    RustLib.instance.api.crateApiCollectionsGetRecord(id: id);
