// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assemble_block`, `connection_label`

/// Stores the version text the diagnostic block reports. Until called the
/// block reads `Version: unknown`.
Future<void> setBuildInfo({required String version}) =>
    RustLib.instance.api.crateApiDiagnosticsSetBuildInfo(version: version);

/// The most recent retained events for one peer, in emission order.
Future<List<LogEventDto>> recentDeviceLogs({
  required String deviceId,
  required int limit,
}) => RustLib.instance.api.crateApiDiagnosticsRecentDeviceLogs(
  deviceId: deviceId,
  limit: limit,
);

/// The most recent retained events that name no peer, in emission order.
Future<List<LogEventDto>> recentLocalLogs({required int limit}) =>
    RustLib.instance.api.crateApiDiagnosticsRecentLocalLogs(limit: limit);

/// Plain-text diagnostic block for one trusted or revoked device.
Future<String> diagnosticBlock({required String deviceId}) =>
    RustLib.instance.api.crateApiDiagnosticsDiagnosticBlock(deviceId: deviceId);
