// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Parses duration text such as "1h 30m" into signed milliseconds; `None` when it does not parse.
int? parseDurationText({required String text}) =>
    RustLib.instance.api.crateApiDurationsParseDurationText(text: text);

/// Why duration text does not parse, or `None` when it does.
String? durationTextError({required String text}) =>
    RustLib.instance.api.crateApiDurationsDurationTextError(text: text);

/// The canonical short form of a duration, for example "1h 30m".
String formatDurationText({required int milliseconds}) => RustLib.instance.api
    .crateApiDurationsFormatDurationText(milliseconds: milliseconds);
