// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_category_id`, `parse_transaction_id`

Future<BootstrapDto> createNewDataset() =>
    RustLib.instance.api.crateApiFinanceCreateNewDataset();

Future<String> createCategory({required String name}) =>
    RustLib.instance.api.crateApiFinanceCreateCategory(name: name);

Future<void> updateCategory({required String id, required String name}) =>
    RustLib.instance.api.crateApiFinanceUpdateCategory(id: id, name: name);

Future<void> deleteCategory({required String id}) =>
    RustLib.instance.api.crateApiFinanceDeleteCategory(id: id);

Future<List<CategoryDto>> listCategories() =>
    RustLib.instance.api.crateApiFinanceListCategories();

Future<String> createTransaction({
  required int occurredAtMs,
  required String categoryId,
  required int amountMinor,
  required String description,
}) => RustLib.instance.api.crateApiFinanceCreateTransaction(
  occurredAtMs: occurredAtMs,
  categoryId: categoryId,
  amountMinor: amountMinor,
  description: description,
);

Future<void> updateTransaction({
  required String id,
  int? occurredAtMs,
  String? categoryId,
  int? amountMinor,
  String? description,
}) => RustLib.instance.api.crateApiFinanceUpdateTransaction(
  id: id,
  occurredAtMs: occurredAtMs,
  categoryId: categoryId,
  amountMinor: amountMinor,
  description: description,
);

Future<void> deleteTransaction({required String id}) =>
    RustLib.instance.api.crateApiFinanceDeleteTransaction(id: id);

Future<List<TransactionDto>> listTransactions({
  required TransactionFilterDto filter,
}) => RustLib.instance.api.crateApiFinanceListTransactions(filter: filter);

Future<AggregateDto> aggregates() =>
    RustLib.instance.api.crateApiFinanceAggregates();
