// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `process_core`

Future<BootstrapDto> initialize({required String dataDir}) =>
    RustLib.instance.api.crateApiLifecycleInitialize(dataDir: dataDir);

Future<BootstrapDto> bootstrapState() =>
    RustLib.instance.api.crateApiLifecycleBootstrapState();

Future<ProjectionDto> projectionState() =>
    RustLib.instance.api.crateApiLifecycleProjectionState();

Future<void> shutdown() => RustLib.instance.api.crateApiLifecycleShutdown();

Stream<BootstrapDto> bootstrapStream() =>
    RustLib.instance.api.crateApiLifecycleBootstrapStream();

Stream<ProjectionDto> projectionStream() =>
    RustLib.instance.api.crateApiLifecycleProjectionStream();

Stream<DataChangedDto> dataChangedStream() =>
    RustLib.instance.api.crateApiLifecycleDataChangedStream();

Stream<BridgeErrorEventDto> errorStream() =>
    RustLib.instance.api.crateApiLifecycleErrorStream();
