// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `initialize_with`, `open_core`, `process_slot`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OpenMode`, `OpenTarget`, `ProcessSlot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<BootstrapDto> initialize({required String dataDir}) =>
    RustLib.instance.api.crateApiLifecycleInitialize(dataDir: dataDir);

Future<BootstrapDto> initializeDesktopNetworked({required String dataDir}) =>
    RustLib.instance.api.crateApiLifecycleInitializeDesktopNetworked(
      dataDir: dataDir,
    );

Future<BootstrapDto> initializeAndroidNetworked({
  required String dataDir,
  required List<int> deviceSeed,
  Uint8List? discoverySecret,
}) => RustLib.instance.api.crateApiLifecycleInitializeAndroidNetworked(
  dataDir: dataDir,
  deviceSeed: deviceSeed,
  discoverySecret: discoverySecret,
);

/// Deliberately abandons this device's local dataset and reopens the core in
/// `NeedsDecision`. Stops pairing and shuts the live core down first; works
/// equally when the last initialization failed (schema cliff), since the
/// directory and key store are remembered from that attempt.
Future<BootstrapDto> resetDataset() =>
    RustLib.instance.api.crateApiLifecycleResetDataset();

/// Why peer networking is not running, when a networked open met a locked or
/// unavailable secure store. `None` means networking is not deferred.
Future<NetworkingDeferredDto?> networkingDeferred() =>
    RustLib.instance.api.crateApiLifecycleNetworkingDeferred();

/// Retries the networking startup deferred by a locked or unavailable secure
/// store and reports whether peer networking is now active. Idempotent: with
/// nothing deferred it succeeds without restarting discovery. A deferral that
/// happened before the device key could be read is retried by reopening the
/// core with the same target, since there is no network stack to restart.
Future<bool> retryNetworking() =>
    RustLib.instance.api.crateApiLifecycleRetryNetworking();

Future<BootstrapDto> bootstrapState() =>
    RustLib.instance.api.crateApiLifecycleBootstrapState();

Future<ProjectionDto> projectionState() =>
    RustLib.instance.api.crateApiLifecycleProjectionState();

Future<void> shutdown() => RustLib.instance.api.crateApiLifecycleShutdown();

Future<void> setForeground({required bool foreground}) =>
    RustLib.instance.api.crateApiLifecycleSetForeground(foreground: foreground);

/// Streams bootstrap state, re-emitting whenever either the lifecycle or the
/// recovery outcome changes so recovery progress is never silent.
Stream<BootstrapDto> bootstrapStream() =>
    RustLib.instance.api.crateApiLifecycleBootstrapStream();

Stream<ProjectionDto> projectionStream() =>
    RustLib.instance.api.crateApiLifecycleProjectionStream();

Stream<DataChangedDto> dataChangedStream() =>
    RustLib.instance.api.crateApiLifecycleDataChangedStream();

Stream<BridgeErrorEventDto> errorStream() =>
    RustLib.instance.api.crateApiLifecycleErrorStream();
