// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `from_core`, `from_core`, `hex_id`, `initialization`, `into_core`, `lifecycle`, `new`, `new`, `safe`, `validation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`

class BootstrapDto {
  final BootstrapKindDto kind;
  final String? rootId;

  const BootstrapDto({required this.kind, this.rootId});

  @override
  int get hashCode => kind.hashCode ^ rootId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BootstrapDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          rootId == other.rootId;
}

enum BootstrapKindDto {
  needsDecision,
  creating,
  joining,
  ready,
  shuttingDown,
  closed,
}

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String? field;
  final String message;

  const BridgeError({required this.kind, this.field, required this.message});

  @override
  int get hashCode => kind.hashCode ^ field.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          field == other.field &&
          message == other.message;
}

class BridgeErrorEventDto {
  final BridgeErrorKind kind;
  final String operation;
  final String message;

  const BridgeErrorEventDto({
    required this.kind,
    required this.operation,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ operation.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeErrorEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          operation == other.operation &&
          message == other.message;
}

enum BridgeErrorKind {
  initialization,
  validation,
  bootstrap,
  persistence,
  projection,
  lifecycle,
  internal,
}

class CollectionDto {
  final String id;
  final String name;
  final String description;

  const CollectionDto({
    required this.id,
    required this.name,
    required this.description,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description;
}

class CollectionSchemaDto {
  final String id;
  final String description;
  final String name;
  final List<FieldDefinitionDto> fields;

  const CollectionSchemaDto({
    required this.id,
    required this.description,
    required this.name,
    required this.fields,
  });

  @override
  int get hashCode =>
      id.hashCode ^ description.hashCode ^ name.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectionSchemaDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description &&
          name == other.name &&
          fields == other.fields;
}

class DataChangedDto {
  final List<DomainKindDto> kinds;
  final List<String> collectionIds;
  final String checkpoint;

  const DataChangedDto({
    required this.kinds,
    required this.collectionIds,
    required this.checkpoint,
  });

  @override
  int get hashCode =>
      kinds.hashCode ^ collectionIds.hashCode ^ checkpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataChangedDto &&
          runtimeType == other.runtimeType &&
          kinds == other.kinds &&
          collectionIds == other.collectionIds &&
          checkpoint == other.checkpoint;
}

class DiagnosticDto {
  final String kind;
  final String entityId;
  final String? fieldId;
  final String message;

  const DiagnosticDto({
    required this.kind,
    required this.entityId,
    this.fieldId,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ entityId.hashCode ^ fieldId.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          entityId == other.entityId &&
          fieldId == other.fieldId &&
          message == other.message;
}

class DisplayMetadataDto {
  final bool multiline;

  const DisplayMetadataDto({required this.multiline});

  static Future<DisplayMetadataDto> default_() =>
      RustLib.instance.api.crateApiModelsDisplayMetadataDtoDefault();

  @override
  int get hashCode => multiline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayMetadataDto &&
          runtimeType == other.runtimeType &&
          multiline == other.multiline;
}

enum DomainKindDto { collections, schemas, records }

class EnumOptionDto {
  final String id;
  final String label;
  final int order;
  final bool deleted;

  const EnumOptionDto({
    required this.id,
    required this.label,
    required this.order,
    required this.deleted,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ order.hashCode ^ deleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumOptionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          order == other.order &&
          deleted == other.deleted;
}

class FieldDefinitionDto {
  final String id;
  final String name;
  final FieldTypeDto fieldType;
  final bool required_;
  final FieldValueDto? defaultValue;
  final ValidationMetadataDto validation;
  final DisplayMetadataDto display;
  final int order;
  final bool deleted;
  final List<EnumOptionDto> enumOptions;

  const FieldDefinitionDto({
    required this.id,
    required this.name,
    required this.fieldType,
    required this.required_,
    this.defaultValue,
    required this.validation,
    required this.display,
    required this.order,
    required this.deleted,
    required this.enumOptions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      fieldType.hashCode ^
      required_.hashCode ^
      defaultValue.hashCode ^
      validation.hashCode ^
      display.hashCode ^
      order.hashCode ^
      deleted.hashCode ^
      enumOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldDefinitionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          fieldType == other.fieldType &&
          required_ == other.required_ &&
          defaultValue == other.defaultValue &&
          validation == other.validation &&
          display == other.display &&
          order == other.order &&
          deleted == other.deleted &&
          enumOptions == other.enumOptions;
}

class FieldTypeDto {
  final FieldTypeKindDto kind;
  final int? scale;

  const FieldTypeDto({required this.kind, this.scale});

  @override
  int get hashCode => kind.hashCode ^ scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldTypeDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          scale == other.scale;
}

enum FieldTypeKindDto {
  text,
  integer,
  fixedDecimal,
  boolean,
  date,
  dateTime,
  duration,
  enum_,
}

class FieldValueDto {
  final FieldValueKindDto kind;
  final int? integerValue;
  final String? textValue;
  final bool? booleanValue;

  const FieldValueDto({
    required this.kind,
    this.integerValue,
    this.textValue,
    this.booleanValue,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      integerValue.hashCode ^
      textValue.hashCode ^
      booleanValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldValueDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          integerValue == other.integerValue &&
          textValue == other.textValue &&
          booleanValue == other.booleanValue;
}

enum FieldValueKindDto {
  null_,
  text,
  integer,
  fixedDecimal,
  boolean,
  date,
  dateTime,
  duration,
  enum_,
}

class PairingCandidateDto {
  final String instanceId;
  final String endpoint;
  final int expiresAtMs;

  const PairingCandidateDto({
    required this.instanceId,
    required this.endpoint,
    required this.expiresAtMs,
  });

  @override
  int get hashCode =>
      instanceId.hashCode ^ endpoint.hashCode ^ expiresAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingCandidateDto &&
          runtimeType == other.runtimeType &&
          instanceId == other.instanceId &&
          endpoint == other.endpoint &&
          expiresAtMs == other.expiresAtMs;
}

enum PairingKindDto {
  idle,
  discoverable,
  connecting,
  awaitingConfirmation,
  committing,
  trusted,
  failed,
}

class PairingStateDto {
  final PairingKindDto kind;
  final String? sessionId;
  final String? sas;
  final String? peerDeviceId;
  final int? deadlineMs;
  final bool localConfirmed;
  final bool remoteConfirmed;
  final String? message;

  const PairingStateDto({
    required this.kind,
    this.sessionId,
    this.sas,
    this.peerDeviceId,
    this.deadlineMs,
    required this.localConfirmed,
    required this.remoteConfirmed,
    this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      sas.hashCode ^
      peerDeviceId.hashCode ^
      deadlineMs.hashCode ^
      localConfirmed.hashCode ^
      remoteConfirmed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingStateDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          sas == other.sas &&
          peerDeviceId == other.peerDeviceId &&
          deadlineMs == other.deadlineMs &&
          localConfirmed == other.localConfirmed &&
          remoteConfirmed == other.remoteConfirmed &&
          message == other.message;
}

enum PeerConnectionKindDto {
  offline,
  searching,
  connected,
  syncing,
  synced,
  error,
}

class ProjectionDto {
  final ProjectionKindDto kind;
  final String? checkpoint;
  final String? message;

  const ProjectionDto({required this.kind, this.checkpoint, this.message});

  @override
  int get hashCode => kind.hashCode ^ checkpoint.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          checkpoint == other.checkpoint &&
          message == other.message;
}

enum ProjectionKindDto {
  unavailable,
  rebuilding,
  projecting,
  ready,
  failed,
  closed,
}

class RecordDto {
  final String id;
  final String collectionId;
  final List<RecordValueDto> values;
  final bool valid;
  final List<DiagnosticDto> diagnostics;

  const RecordDto({
    required this.id,
    required this.collectionId,
    required this.values,
    required this.valid,
    required this.diagnostics,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      collectionId.hashCode ^
      values.hashCode ^
      valid.hashCode ^
      diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          collectionId == other.collectionId &&
          values == other.values &&
          valid == other.valid &&
          diagnostics == other.diagnostics;
}

class RecordValueDto {
  final String fieldId;
  final FieldValueDto value;

  const RecordValueDto({required this.fieldId, required this.value});

  @override
  int get hashCode => fieldId.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordValueDto &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          value == other.value;
}

enum SyncStatusDto { offline, searching, connected, syncing, synced, error }

class TrustedDeviceDto {
  final String deviceId;
  final String friendlyName;
  final int pairedAtMs;
  final int? lastSeenMs;
  final int? lastSyncMs;
  final bool revoked;
  final PeerConnectionKindDto connection;

  const TrustedDeviceDto({
    required this.deviceId,
    required this.friendlyName,
    required this.pairedAtMs,
    this.lastSeenMs,
    this.lastSyncMs,
    required this.revoked,
    required this.connection,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      friendlyName.hashCode ^
      pairedAtMs.hashCode ^
      lastSeenMs.hashCode ^
      lastSyncMs.hashCode ^
      revoked.hashCode ^
      connection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedDeviceDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          friendlyName == other.friendlyName &&
          pairedAtMs == other.pairedAtMs &&
          lastSeenMs == other.lastSeenMs &&
          lastSyncMs == other.lastSyncMs &&
          revoked == other.revoked &&
          connection == other.connection;
}

class ValidationMetadataDto {
  final int? minInteger;
  final int? maxInteger;
  final int? minLength;
  final int? maxLength;

  const ValidationMetadataDto({
    this.minInteger,
    this.maxInteger,
    this.minLength,
    this.maxLength,
  });

  static Future<ValidationMetadataDto> default_() =>
      RustLib.instance.api.crateApiModelsValidationMetadataDtoDefault();

  @override
  int get hashCode =>
      minInteger.hashCode ^
      maxInteger.hashCode ^
      minLength.hashCode ^
      maxLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidationMetadataDto &&
          runtimeType == other.runtimeType &&
          minInteger == other.minInteger &&
          maxInteger == other.maxInteger &&
          minLength == other.minLength &&
          maxLength == other.maxLength;
}
