// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `from_core`, `from_core`, `hex_id`, `initialization`, `lifecycle`, `new`, `new`, `safe`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class AggregateDto {
  final int balanceMinor;
  final int incomeMinor;
  final int expenseMinor;
  final int transactionCount;

  const AggregateDto({
    required this.balanceMinor,
    required this.incomeMinor,
    required this.expenseMinor,
    required this.transactionCount,
  });

  static Future<AggregateDto> default_() =>
      RustLib.instance.api.crateApiModelsAggregateDtoDefault();

  @override
  int get hashCode =>
      balanceMinor.hashCode ^
      incomeMinor.hashCode ^
      expenseMinor.hashCode ^
      transactionCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AggregateDto &&
          runtimeType == other.runtimeType &&
          balanceMinor == other.balanceMinor &&
          incomeMinor == other.incomeMinor &&
          expenseMinor == other.expenseMinor &&
          transactionCount == other.transactionCount;
}

class BootstrapDto {
  final BootstrapKindDto kind;
  final String? rootId;

  const BootstrapDto({required this.kind, this.rootId});

  @override
  int get hashCode => kind.hashCode ^ rootId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BootstrapDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          rootId == other.rootId;
}

enum BootstrapKindDto {
  needsDecision,
  creating,
  joining,
  ready,
  shuttingDown,
  closed,
}

class BridgeError implements FrbException {
  final BridgeErrorKind kind;
  final String? field;
  final String message;

  const BridgeError({required this.kind, this.field, required this.message});

  @override
  int get hashCode => kind.hashCode ^ field.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          field == other.field &&
          message == other.message;
}

class BridgeErrorEventDto {
  final BridgeErrorKind kind;
  final String operation;
  final String message;

  const BridgeErrorEventDto({
    required this.kind,
    required this.operation,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ operation.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeErrorEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          operation == other.operation &&
          message == other.message;
}

enum BridgeErrorKind {
  initialization,
  validation,
  bootstrap,
  persistence,
  projection,
  lifecycle,
  internal,
}

class CategoryDto {
  final String id;
  final String name;

  const CategoryDto({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class DataChangedDto {
  final List<DomainKindDto> kinds;
  final String checkpoint;

  const DataChangedDto({required this.kinds, required this.checkpoint});

  @override
  int get hashCode => kinds.hashCode ^ checkpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataChangedDto &&
          runtimeType == other.runtimeType &&
          kinds == other.kinds &&
          checkpoint == other.checkpoint;
}

enum DomainKindDto { categories, transactions }

class PairingCandidateDto {
  final String instanceId;
  final String endpoint;
  final int expiresAtMs;

  const PairingCandidateDto({
    required this.instanceId,
    required this.endpoint,
    required this.expiresAtMs,
  });

  @override
  int get hashCode =>
      instanceId.hashCode ^ endpoint.hashCode ^ expiresAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingCandidateDto &&
          runtimeType == other.runtimeType &&
          instanceId == other.instanceId &&
          endpoint == other.endpoint &&
          expiresAtMs == other.expiresAtMs;
}

enum PairingKindDto {
  idle,
  discoverable,
  connecting,
  awaitingConfirmation,
  committing,
  trusted,
  failed,
}

class PairingStateDto {
  final PairingKindDto kind;
  final String? sessionId;
  final String? sas;
  final String? peerDeviceId;
  final int? deadlineMs;
  final bool localConfirmed;
  final bool remoteConfirmed;
  final String? message;

  const PairingStateDto({
    required this.kind,
    this.sessionId,
    this.sas,
    this.peerDeviceId,
    this.deadlineMs,
    required this.localConfirmed,
    required this.remoteConfirmed,
    this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      sas.hashCode ^
      peerDeviceId.hashCode ^
      deadlineMs.hashCode ^
      localConfirmed.hashCode ^
      remoteConfirmed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingStateDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          sas == other.sas &&
          peerDeviceId == other.peerDeviceId &&
          deadlineMs == other.deadlineMs &&
          localConfirmed == other.localConfirmed &&
          remoteConfirmed == other.remoteConfirmed &&
          message == other.message;
}

enum PeerConnectionKindDto {
  offline,
  searching,
  connected,
  syncing,
  synced,
  error,
}

class ProjectionDto {
  final ProjectionKindDto kind;
  final String? checkpoint;
  final String? message;

  const ProjectionDto({required this.kind, this.checkpoint, this.message});

  @override
  int get hashCode => kind.hashCode ^ checkpoint.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          checkpoint == other.checkpoint &&
          message == other.message;
}

enum ProjectionKindDto {
  unavailable,
  rebuilding,
  projecting,
  ready,
  failed,
  closed,
}

enum SyncStatusDto { offline, searching, connected, syncing, synced, error }

class TransactionDto {
  final String id;
  final int occurredAtMs;
  final String categoryId;
  final String? categoryName;
  final bool categoryAvailable;
  final int amountMinor;
  final String description;

  const TransactionDto({
    required this.id,
    required this.occurredAtMs,
    required this.categoryId,
    this.categoryName,
    required this.categoryAvailable,
    required this.amountMinor,
    required this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      occurredAtMs.hashCode ^
      categoryId.hashCode ^
      categoryName.hashCode ^
      categoryAvailable.hashCode ^
      amountMinor.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          occurredAtMs == other.occurredAtMs &&
          categoryId == other.categoryId &&
          categoryName == other.categoryName &&
          categoryAvailable == other.categoryAvailable &&
          amountMinor == other.amountMinor &&
          description == other.description;
}

class TransactionFilterDto {
  final String? text;
  final String? categoryId;
  final int? fromMs;
  final int? throughMs;

  const TransactionFilterDto({
    this.text,
    this.categoryId,
    this.fromMs,
    this.throughMs,
  });

  static Future<TransactionFilterDto> default_() =>
      RustLib.instance.api.crateApiModelsTransactionFilterDtoDefault();

  @override
  int get hashCode =>
      text.hashCode ^
      categoryId.hashCode ^
      fromMs.hashCode ^
      throughMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionFilterDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          categoryId == other.categoryId &&
          fromMs == other.fromMs &&
          throughMs == other.throughMs;
}

class TrustedDeviceDto {
  final String deviceId;
  final String friendlyName;
  final int pairedAtMs;
  final int? lastSeenMs;
  final int? lastSyncMs;
  final bool revoked;
  final PeerConnectionKindDto connection;

  const TrustedDeviceDto({
    required this.deviceId,
    required this.friendlyName,
    required this.pairedAtMs,
    this.lastSeenMs,
    this.lastSyncMs,
    required this.revoked,
    required this.connection,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      friendlyName.hashCode ^
      pairedAtMs.hashCode ^
      lastSeenMs.hashCode ^
      lastSyncMs.hashCode ^
      revoked.hashCode ^
      connection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedDeviceDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          friendlyName == other.friendlyName &&
          pairedAtMs == other.pairedAtMs &&
          lastSeenMs == other.lastSeenMs &&
          lastSyncMs == other.lastSyncMs &&
          revoked == other.revoked &&
          connection == other.connection;
}
