// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_16`, `encode_16`, `forward_connection_states`, `nibble`, `reconnect_allowed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeviceRows`

Future<String> startPairing({required int durationMs}) =>
    RustLib.instance.api.crateApiPairingStartPairing(durationMs: durationMs);

Future<void> stopPairing() => RustLib.instance.api.crateApiPairingStopPairing();

Future<PairingStateDto> pairingState() =>
    RustLib.instance.api.crateApiPairingPairingState();

Future<List<PairingCandidateDto>> pairingCandidates() =>
    RustLib.instance.api.crateApiPairingPairingCandidates();

Future<String> connectPairingCandidate({
  required String instanceId,
  required String endpoint,
  required int expiresAtMs,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiPairingConnectPairingCandidate(
  instanceId: instanceId,
  endpoint: endpoint,
  expiresAtMs: expiresAtMs,
  timeoutMs: timeoutMs,
);

Future<void> confirmPairing({required String sessionId}) =>
    RustLib.instance.api.crateApiPairingConfirmPairing(sessionId: sessionId);

Future<void> rejectPairing({String? sessionId}) =>
    RustLib.instance.api.crateApiPairingRejectPairing(sessionId: sessionId);

Future<List<TrustedDeviceDto>> trustedDevices() =>
    RustLib.instance.api.crateApiPairingTrustedDevices();

/// This device's DeviceId and the name it presents in the pairing hello;
/// `None` when no identity exists yet (local-only mode).
Future<LocalDeviceDto?> localDevice() =>
    RustLib.instance.api.crateApiPairingLocalDevice();

/// Dials a trusted, non-revoked peer now, bypassing backoff and initiator
/// preference. An attempt already in flight is not doubled, and a live
/// session is kept.
Future<void> connectDeviceNow({required String deviceId}) =>
    RustLib.instance.api.crateApiPairingConnectDeviceNow(deviceId: deviceId);

/// Dials a trusted, non-revoked peer at a user-typed address. Address and
/// connection problems are outcomes; paused and unknown/revoked devices are
/// errors.
Future<ManualConnectOutcomeDto> connectDeviceAtAddress({
  required String deviceId,
  required String address,
}) => RustLib.instance.api.crateApiPairingConnectDeviceAtAddress(
  deviceId: deviceId,
  address: address,
);

/// Addresses at which a paired device on the same LAN can reach this one, as
/// `ip:port`; empty when networking has no bound sync port.
Future<List<String>> localSyncAddresses() =>
    RustLib.instance.api.crateApiPairingLocalSyncAddresses();

Future<NetworkPreferencesDto> networkPreferences() =>
    RustLib.instance.api.crateApiPairingNetworkPreferences();

/// Returns the stored preferences so Flutter renders what Rust holds.
Future<NetworkPreferencesDto> setDiscoverable({required bool discoverable}) =>
    RustLib.instance.api.crateApiPairingSetDiscoverable(
      discoverable: discoverable,
    );

/// Returns the stored preferences so Flutter renders what Rust holds.
Future<NetworkPreferencesDto> setSyncEnabled({required bool syncEnabled}) =>
    RustLib.instance.api.crateApiPairingSetSyncEnabled(
      syncEnabled: syncEnabled,
    );

Future<SyncStatusDto> syncStatus() =>
    RustLib.instance.api.crateApiPairingSyncStatus();

Stream<List<TrustedDeviceDto>> connectionStateStream() =>
    RustLib.instance.api.crateApiPairingConnectionStateStream();

Stream<SyncStatusDto> syncStatusStream() =>
    RustLib.instance.api.crateApiPairingSyncStatusStream();

/// Names this device; peers learn the name on their next session. Fails
/// with a validation error for a blank name or one over 64 UTF-8 bytes.
Future<LocalDeviceDto> setLocalDeviceName({required String name}) =>
    RustLib.instance.api.crateApiPairingSetLocalDeviceName(name: name);

/// Sets a trusted device's local nickname; an empty name clears it.
Future<bool> renameTrustedDevice({
  required String deviceId,
  required String name,
}) => RustLib.instance.api.crateApiPairingRenameTrustedDevice(
  deviceId: deviceId,
  name: name,
);

/// Permanently deletes a revoked device record. Returns `false` when the
/// record is unknown or still trusted.
Future<bool> deleteRevokedDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiPairingDeleteRevokedDevice(deviceId: deviceId);

Future<RevocationOutcomeDto> revokeTrustedDevice({
  required String deviceId,
  required int nowMs,
}) => RustLib.instance.api.crateApiPairingRevokeTrustedDevice(
  deviceId: deviceId,
  nowMs: nowMs,
);

/// Retries discovery-secret rotation after a revocation whose rotation stage
/// failed. Returns the new epoch.
Future<int> rotateDiscoverySecret({required int nowMs}) =>
    RustLib.instance.api.crateApiPairingRotateDiscoverySecret(nowMs: nowMs);

Stream<PairingStateDto> pairingStateStream() =>
    RustLib.instance.api.crateApiPairingPairingStateStream();

Stream<List<PairingCandidateDto>> pairingCandidatesStream() =>
    RustLib.instance.api.crateApiPairingPairingCandidatesStream();
