// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_16`, `encode_16`, `nibble`

Future<String> startPairing({required int durationMs}) =>
    RustLib.instance.api.crateApiPairingStartPairing(durationMs: durationMs);

Future<void> stopPairing() => RustLib.instance.api.crateApiPairingStopPairing();

Future<PairingStateDto> pairingState() =>
    RustLib.instance.api.crateApiPairingPairingState();

Future<List<PairingCandidateDto>> pairingCandidates() =>
    RustLib.instance.api.crateApiPairingPairingCandidates();

Future<String> connectPairingCandidate({
  required String instanceId,
  required String endpoint,
  required int expiresAtMs,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiPairingConnectPairingCandidate(
  instanceId: instanceId,
  endpoint: endpoint,
  expiresAtMs: expiresAtMs,
  timeoutMs: timeoutMs,
);

Future<void> confirmPairing({required String sessionId}) =>
    RustLib.instance.api.crateApiPairingConfirmPairing(sessionId: sessionId);

Future<void> rejectPairing({String? sessionId}) =>
    RustLib.instance.api.crateApiPairingRejectPairing(sessionId: sessionId);

Future<List<TrustedDeviceDto>> trustedDevices() =>
    RustLib.instance.api.crateApiPairingTrustedDevices();

Future<SyncStatusDto> syncStatus() =>
    RustLib.instance.api.crateApiPairingSyncStatus();

Future<Uint8List?> discoverySecretForPlatform() =>
    RustLib.instance.api.crateApiPairingDiscoverySecretForPlatform();

Stream<List<TrustedDeviceDto>> connectionStateStream() =>
    RustLib.instance.api.crateApiPairingConnectionStateStream();

Stream<SyncStatusDto> syncStatusStream() =>
    RustLib.instance.api.crateApiPairingSyncStatusStream();

Future<bool> renameTrustedDevice({
  required String deviceId,
  required String name,
}) => RustLib.instance.api.crateApiPairingRenameTrustedDevice(
  deviceId: deviceId,
  name: name,
);

Future<RevocationOutcomeDto> revokeTrustedDevice({
  required String deviceId,
  required int nowMs,
}) => RustLib.instance.api.crateApiPairingRevokeTrustedDevice(
  deviceId: deviceId,
  nowMs: nowMs,
);

/// Retries discovery-secret rotation after a revocation whose rotation stage
/// failed. Returns the new epoch.
Future<int> rotateDiscoverySecret({required int nowMs}) =>
    RustLib.instance.api.crateApiPairingRotateDiscoverySecret(nowMs: nowMs);

Stream<PairingStateDto> pairingStateStream() =>
    RustLib.instance.api.crateApiPairingPairingStateStream();

Stream<List<PairingCandidateDto>> pairingCandidatesStream() =>
    RustLib.instance.api.crateApiPairingPairingCandidatesStream();
