// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `comparison`, `decode_node`, `empty_node`, `encode_node`, `missing`, `rounding`, `validation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`

Future<String> createComputedField({
  required ComputedFieldDefinitionDto definition,
}) => RustLib.instance.api.crateApiQueriesCreateComputedField(
  definition: definition,
);

Future<void> updateComputedField({
  required ComputedFieldDefinitionDto definition,
}) => RustLib.instance.api.crateApiQueriesUpdateComputedField(
  definition: definition,
);

Future<void> removeComputedField({
  required String collectionId,
  required String id,
}) => RustLib.instance.api.crateApiQueriesRemoveComputedField(
  collectionId: collectionId,
  id: id,
);

Future<void> reorderComputedFields({
  required String collectionId,
  required List<String> ids,
}) => RustLib.instance.api.crateApiQueriesReorderComputedFields(
  collectionId: collectionId,
  ids: ids,
);

Future<List<ComputedFieldDefinitionDto>> listComputedFields({
  required String collectionId,
}) => RustLib.instance.api.crateApiQueriesListComputedFields(
  collectionId: collectionId,
);

Future<String> createQueryDefinition({
  required QueryDefinitionDto definition,
}) => RustLib.instance.api.crateApiQueriesCreateQueryDefinition(
  definition: definition,
);

Future<void> updateQueryDefinition({required QueryDefinitionDto definition}) =>
    RustLib.instance.api.crateApiQueriesUpdateQueryDefinition(
      definition: definition,
    );

Future<void> removeQueryDefinition({
  required String collectionId,
  required String id,
}) => RustLib.instance.api.crateApiQueriesRemoveQueryDefinition(
  collectionId: collectionId,
  id: id,
);

Future<void> reorderQueryDefinitions({
  required String collectionId,
  required List<String> ids,
}) => RustLib.instance.api.crateApiQueriesReorderQueryDefinitions(
  collectionId: collectionId,
  ids: ids,
);

Future<List<QueryDefinitionDto>> listQueryDefinitions({
  required String collectionId,
}) => RustLib.instance.api.crateApiQueriesListQueryDefinitions(
  collectionId: collectionId,
);

Future<void> validateCollectionQuery({required CollectionQueryDto query}) =>
    RustLib.instance.api.crateApiQueriesValidateCollectionQuery(query: query);

Future<QueryResultDto> executeCollectionQuery({
  required CollectionQueryDto query,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiQueriesExecuteCollectionQuery(
  query: query,
  nowUtcMs: nowUtcMs,
);

Future<QueryResultDto> executeQueryDefinition({
  required String collectionId,
  required String id,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiQueriesExecuteQueryDefinition(
  collectionId: collectionId,
  id: id,
  nowUtcMs: nowUtcMs,
);
