// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `saved_id`, `saved_ids`, `sort_from_dto`, `sort_to_dto`, `validation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `try_from`

Future<List<ViewDto>> listViews({
  required String collectionId,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiViewsListViews(
  collectionId: collectionId,
  nowUtcMs: nowUtcMs,
);

/// Creates a saved view after the last one and returns its id.
Future<String> createView({
  required String collectionId,
  required String name,
  required ViewBodyDto body,
}) => RustLib.instance.api.crateApiViewsCreateView(
  collectionId: collectionId,
  name: name,
  body: body,
);

Future<void> updateView({
  required String collectionId,
  required String viewId,
  required ViewBodyDto body,
}) => RustLib.instance.api.crateApiViewsUpdateView(
  collectionId: collectionId,
  viewId: viewId,
  body: body,
);

Future<void> renameView({
  required String collectionId,
  required String viewId,
  required String name,
}) => RustLib.instance.api.crateApiViewsRenameView(
  collectionId: collectionId,
  viewId: viewId,
  name: name,
);

/// Stores the order of the saved views; `"all"` is always first and is skipped.
Future<void> reorderViews({
  required String collectionId,
  required List<String> ids,
}) => RustLib.instance.api.crateApiViewsReorderViews(
  collectionId: collectionId,
  ids: ids,
);

Future<void> removeView({
  required String collectionId,
  required String viewId,
}) => RustLib.instance.api.crateApiViewsRemoveView(
  collectionId: collectionId,
  viewId: viewId,
);

/// Executes a saved view, or All for `"all"`.
Future<ViewResultDto> executeView({
  required String collectionId,
  required String viewId,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiViewsExecuteView(
  collectionId: collectionId,
  viewId: viewId,
  nowUtcMs: nowUtcMs,
);

/// Executes an unsaved body; nothing is written.
Future<ViewResultDto> executeViewBody({
  required String collectionId,
  required ViewBodyDto body,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiViewsExecuteViewBody(
  collectionId: collectionId,
  body: body,
  nowUtcMs: nowUtcMs,
);

/// A view body: an optional Boolean filter and up to three sort clauses.
class ViewBodyDto {
  final ExpressionDto? filter;
  final List<SortClauseDto> sorting;

  const ViewBodyDto({this.filter, required this.sorting});

  @override
  int get hashCode => filter.hashCode ^ sorting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewBodyDto &&
          runtimeType == other.runtimeType &&
          filter == other.filter &&
          sorting == other.sorting;
}

/// One entry of a collection's view listing. All comes first with id `"all"`.
class ViewDto {
  final String id;
  final String name;

  /// `None` when the stored body cannot be read (unsupported version).
  final ViewBodyDto? body;
  final int order;

  /// `None` for a broken view.
  final int? count;

  /// Why the view is broken; `None` when it executes.
  final String? broken;

  /// The stored sort minus clauses that no longer resolve; created desc when none is left.
  final List<SortClauseDto> effectiveSort;

  const ViewDto({
    required this.id,
    required this.name,
    this.body,
    required this.order,
    this.count,
    this.broken,
    required this.effectiveSort,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      body.hashCode ^
      order.hashCode ^
      count.hashCode ^
      broken.hashCode ^
      effectiveSort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          body == other.body &&
          order == other.order &&
          count == other.count &&
          broken == other.broken &&
          effectiveSort == other.effectiveSort;
}

class ViewResultDto {
  final List<String> ids;
  final int count;

  const ViewResultDto({required this.ids, required this.count});

  @override
  int get hashCode => ids.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewResultDto &&
          runtimeType == other.runtimeType &&
          ids == other.ids &&
          count == other.count;
}
