// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `manager`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Current status of the model set.
ModelStatusDto modelStatus({required String modelsDir}) =>
    RustLib.instance.api.crateApiVoiceModelsModelStatus(modelsDir: modelsDir);

/// Free bytes on the volume holding the models, when known.
int? modelFreeStorageBytes({required String modelsDir}) => RustLib.instance.api
    .crateApiVoiceModelsModelFreeStorageBytes(modelsDir: modelsDir);

/// Starts or resumes the download. Refuses with `NotEnoughStorage` when it won't fit.
Future<void> startModelDownload({required String modelsDir}) => RustLib
    .instance
    .api
    .crateApiVoiceModelsStartModelDownload(modelsDir: modelsDir);

/// Pauses the download, keeping the bytes already stored.
Future<void> pauseModelDownload({required String modelsDir}) => RustLib
    .instance
    .api
    .crateApiVoiceModelsPauseModelDownload(modelsDir: modelsDir);

/// Cancels the download, dropping partial bytes.
Future<void> cancelModelDownload({required String modelsDir}) => RustLib
    .instance
    .api
    .crateApiVoiceModelsCancelModelDownload(modelsDir: modelsDir);

/// Deletes every model file, returning the bytes freed.
Future<int> deleteModels({required String modelsDir}) =>
    RustLib.instance.api.crateApiVoiceModelsDeleteModels(modelsDir: modelsDir);

/// Deletes the models, then starts a fresh download.
Future<void> redownloadModels({required String modelsDir}) => RustLib
    .instance
    .api
    .crateApiVoiceModelsRedownloadModels(modelsDir: modelsDir);

/// Marks a voice turn as running; delete and re-download refuse meanwhile.
void setVoiceTurnActive({required String modelsDir, required bool active}) =>
    RustLib.instance.api.crateApiVoiceModelsSetVoiceTurnActive(
      modelsDir: modelsDir,
      active: active,
    );

/// Streams the current status and every change.
Stream<ModelStatusDto> modelStatusEvents({required String modelsDir}) => RustLib
    .instance
    .api
    .crateApiVoiceModelsModelStatusEvents(modelsDir: modelsDir);

class ModelErrorDto implements FrbException {
  final ModelErrorKindDto kind;
  final String message;

  /// Set for `HttpStatus`.
  final int? httpStatus;

  /// Set for `NotEnoughStorage`: download plus headroom.
  final int? neededBytes;

  const ModelErrorDto({
    required this.kind,
    required this.message,
    this.httpStatus,
    this.neededBytes,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      httpStatus.hashCode ^
      neededBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelErrorDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          httpStatus == other.httpStatus &&
          neededBytes == other.neededBytes;
}

enum ModelErrorKindDto {
  network,
  httpStatus,
  checksum,
  notEnoughStorage,
  io,
  voiceTurnActive,
}

/// The model set's state, flattened for Dart.
class ModelStatusDto {
  final ModelStatusKindDto kind;

  /// Bytes on disk over the whole set (verified plus partial).
  final int doneBytes;

  /// Sum of every manifest file.
  final int totalBytes;

  /// Sum of files not yet verified: the size a download offer shows.
  final int remainingBytes;
  final int? secondsLeft;

  /// Set for `Failed`.
  final ModelErrorDto? error;

  const ModelStatusDto({
    required this.kind,
    required this.doneBytes,
    required this.totalBytes,
    required this.remainingBytes,
    this.secondsLeft,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      doneBytes.hashCode ^
      totalBytes.hashCode ^
      remainingBytes.hashCode ^
      secondsLeft.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelStatusDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          doneBytes == other.doneBytes &&
          totalBytes == other.totalBytes &&
          remainingBytes == other.remainingBytes &&
          secondsLeft == other.secondsLeft &&
          error == other.error;
}

enum ModelStatusKindDto { notDownloaded, downloading, paused, ready, failed }
