// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dictation`, `entry_dto`, `failed`, `field`, `patch`, `request`, `transcript`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Whether this build has the on-device engine. True whether or not the models are downloaded,
/// so the first-use download flow can run.
bool voiceNativeAvailable() =>
    RustLib.instance.api.crateApiVoiceVoiceNativeAvailable();

/// Starts loading the instruction model in the background when the models are ready. Idempotent.
void voicePrepare({required String modelsDir}) =>
    RustLib.instance.api.crateApiVoiceVoicePrepare(modelsDir: modelsDir);

/// Transcribes and fills one turn of 16 kHz mono PCM16 audio. The sink receives the transcript,
/// then the patch or a failure, and closes.
Stream<VoiceTurnEventDto> voiceFillTurn({
  required String modelsDir,
  required List<int> pcm,
  required VoiceFillRequestDto request,
}) => RustLib.instance.api.crateApiVoiceVoiceFillTurn(
  modelsDir: modelsDir,
  pcm: pcm,
  request: request,
);

/// Transcribes one turn of 16 kHz mono PCM16 audio and cleans it for dictation into one field.
/// The sink receives the transcript, then the dictation or a failure, and closes. `language` is
/// the voice language code; anything but "es" reads as English.
Stream<VoiceTurnEventDto> voiceDictateTurn({
  required String modelsDir,
  required List<int> pcm,
  required String language,
}) => RustLib.instance.api.crateApiVoiceVoiceDictateTurn(
  modelsDir: modelsDir,
  pcm: pcm,
  language: language,
);

/// Stops the running turn at the next opportunity; it fails with `Cancelled`.
void voiceCancel() => RustLib.instance.api.crateApiVoiceVoiceCancel();

/// Ends the running dictation turn's cleanup at the next token; the turn returns its transcript
/// unchanged. Unlike [`voice_cancel`] it keeps the transcript, and it is a no-op for fill turns,
/// before the transcript exists and after the result.
void voiceSkipCleanup() => RustLib.instance.api.crateApiVoiceVoiceSkipCleanup();

/// Releases the instruction model (backgrounded app or memory pressure).
void voiceRelease() => RustLib.instance.api.crateApiVoiceVoiceRelease();

/// A dictation turn's cleaned text. `removed` holds the indexes of the transcript's
/// whitespace-separated tokens that the cleanup dropped.
class VoiceDictationDto {
  final String cleaned;
  final Uint32List removed;

  const VoiceDictationDto({required this.cleaned, required this.removed});

  @override
  int get hashCode => cleaned.hashCode ^ removed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceDictationDto &&
          runtimeType == other.runtimeType &&
          cleaned == other.cleaned &&
          removed == other.removed;
}

/// A draft value, as display text.
class VoiceDraftValueDto {
  final String fieldId;
  final String text;

  const VoiceDraftValueDto({required this.fieldId, required this.text});

  @override
  int get hashCode => fieldId.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceDraftValueDto &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          text == other.text;
}

enum VoiceErrorKindDto {
  noSpeech,
  nothingMatched,
  modelLoadFailed,
  lowMemory,
  cancelled,
}

/// One active field, as the engine sees it.
class VoiceFieldDto {
  final String id;
  final String name;
  final FieldTypeKindDto kind;
  final int? scale;
  final bool required_;
  final List<VoiceOptionDto> options;
  final int? maxLength;

  const VoiceFieldDto({
    required this.id,
    required this.name,
    required this.kind,
    this.scale,
    required this.required_,
    required this.options,
    this.maxLength,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      scale.hashCode ^
      required_.hashCode ^
      options.hashCode ^
      maxLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceFieldDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          scale == other.scale &&
          required_ == other.required_ &&
          options == other.options &&
          maxLength == other.maxLength;
}

/// What one turn fills, with the device's local date, minute and UTC offset.
class VoiceFillRequestDto {
  final String collectionId;
  final List<VoiceFieldDto> fields;
  final List<VoiceDraftValueDto> draft;
  final int year;
  final int month;
  final int day;
  final int minuteOfDay;
  final int utcOffsetMinutes;

  /// The voice language code: "en" or "es". Anything else reads as English.
  final String language;

  const VoiceFillRequestDto({
    required this.collectionId,
    required this.fields,
    required this.draft,
    required this.year,
    required this.month,
    required this.day,
    required this.minuteOfDay,
    required this.utcOffsetMinutes,
    required this.language,
  });

  @override
  int get hashCode =>
      collectionId.hashCode ^
      fields.hashCode ^
      draft.hashCode ^
      year.hashCode ^
      month.hashCode ^
      day.hashCode ^
      minuteOfDay.hashCode ^
      utcOffsetMinutes.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceFillRequestDto &&
          runtimeType == other.runtimeType &&
          collectionId == other.collectionId &&
          fields == other.fields &&
          draft == other.draft &&
          year == other.year &&
          month == other.month &&
          day == other.day &&
          minuteOfDay == other.minuteOfDay &&
          utcOffsetMinutes == other.utcOffsetMinutes &&
          language == other.language;
}

/// One live option of a Choice field.
class VoiceOptionDto {
  final String id;
  final String label;

  const VoiceOptionDto({required this.id, required this.label});

  @override
  int get hashCode => id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceOptionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label;
}

class VoicePatchEntryDto {
  final String fieldId;
  final FieldValueDto value;
  final String evidence;

  const VoicePatchEntryDto({
    required this.fieldId,
    required this.value,
    required this.evidence,
  });

  @override
  int get hashCode => fieldId.hashCode ^ value.hashCode ^ evidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoicePatchEntryDto &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          value == other.value &&
          evidence == other.evidence;
}

/// One event of a turn: the transcript first, then either the patch (fill turn), the dictation
/// (dictation turn) or a failure.
class VoiceTurnEventDto {
  final String? transcript;
  final List<VoicePatchEntryDto>? patch;
  final VoiceDictationDto? dictation;
  final VoiceErrorKindDto? error;

  const VoiceTurnEventDto({
    this.transcript,
    this.patch,
    this.dictation,
    this.error,
  });

  @override
  int get hashCode =>
      transcript.hashCode ^
      patch.hashCode ^
      dictation.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceTurnEventDto &&
          runtimeType == other.runtimeType &&
          transcript == other.transcript &&
          patch == other.patch &&
          dictation == other.dictation &&
          error == other.error;
}
