// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `missing`, `validation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`

Future<List<WidgetDefinitionDto>> listWidgets({required String collectionId}) =>
    RustLib.instance.api.crateApiWidgetsListWidgets(collectionId: collectionId);

/// Reads one widget including tombstoned and unsupported definitions, so preserved data can be
/// inspected and edited through safe metadata changes only.
Future<WidgetDefinitionDto?> getWidget({
  required String collectionId,
  required String id,
}) => RustLib.instance.api.crateApiWidgetsGetWidget(
  collectionId: collectionId,
  id: id,
);

Future<String> createWidget({required WidgetDefinitionDto definition}) =>
    RustLib.instance.api.crateApiWidgetsCreateWidget(definition: definition);

Future<void> updateWidget({required WidgetUpdateDto update}) =>
    RustLib.instance.api.crateApiWidgetsUpdateWidget(update: update);

Future<void> removeWidget({required String collectionId, required String id}) =>
    RustLib.instance.api.crateApiWidgetsRemoveWidget(
      collectionId: collectionId,
      id: id,
    );

Future<void> reorderWidgets({
  required String collectionId,
  required List<String> ids,
}) => RustLib.instance.api.crateApiWidgetsReorderWidgets(
  collectionId: collectionId,
  ids: ids,
);

/// The descriptor registry this build implements. Widget types not listed here are still valid
/// synchronized data; `get_widget_descriptor` reports them as unsupported instead of failing.
Future<List<WidgetDescriptorDto>> listWidgetDescriptors() =>
    RustLib.instance.api.crateApiWidgetsListWidgetDescriptors();

/// Resolves one widget type against the local registry. Unknown types yield an unsupported
/// descriptor with no accepted shapes rather than an error, so the UI can render a placeholder.
Future<WidgetDescriptorDto> getWidgetDescriptor({required String widgetType}) =>
    RustLib.instance.api.crateApiWidgetsGetWidgetDescriptor(
      widgetType: widgetType,
    );

Future<WidgetEvaluationDto> evaluateWidget({
  required String collectionId,
  required String id,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiWidgetsEvaluateWidget(
  collectionId: collectionId,
  id: id,
  nowUtcMs: nowUtcMs,
);

/// Evaluates every active widget of a collection. Duplicate query references are executed once per
/// call. A failing widget returns a typed error entry; the others still return results.
Future<List<WidgetEvaluationDto>> evaluateWidgets({
  required String collectionId,
  required int nowUtcMs,
}) => RustLib.instance.api.crateApiWidgetsEvaluateWidgets(
  collectionId: collectionId,
  nowUtcMs: nowUtcMs,
);

Future<List<DiagnosticDto>> widgetDiagnostics({required String id}) =>
    RustLib.instance.api.crateApiWidgetsWidgetDiagnostics(id: id);
