// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/finance.dart';
import 'api/lifecycle.dart';
import 'api/models.dart';
import 'api/pairing.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  RustStreamSink<BootstrapDto> dco_decode_StreamSink_bootstrap_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeErrorEventDto>
  dco_decode_StreamSink_bridge_error_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<DataChangedDto> dco_decode_StreamSink_data_changed_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<PairingCandidateDto>>
  dco_decode_StreamSink_list_pairing_candidate_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<List<TrustedDeviceDto>>
  dco_decode_StreamSink_list_trusted_device_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<PairingStateDto> dco_decode_StreamSink_pairing_state_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProjectionDto> dco_decode_StreamSink_projection_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncStatusDto> dco_decode_StreamSink_sync_status_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AggregateDto dco_decode_aggregate_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BootstrapDto dco_decode_bootstrap_dto(dynamic raw);

  @protected
  BootstrapKindDto dco_decode_bootstrap_kind_dto(dynamic raw);

  @protected
  TransactionFilterDto dco_decode_box_autoadd_transaction_filter_dto(
    dynamic raw,
  );

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorEventDto dco_decode_bridge_error_event_dto(dynamic raw);

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw);

  @protected
  CategoryDto dco_decode_category_dto(dynamic raw);

  @protected
  DataChangedDto dco_decode_data_changed_dto(dynamic raw);

  @protected
  DomainKindDto dco_decode_domain_kind_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<CategoryDto> dco_decode_list_category_dto(dynamic raw);

  @protected
  List<DomainKindDto> dco_decode_list_domain_kind_dto(dynamic raw);

  @protected
  List<PairingCandidateDto> dco_decode_list_pairing_candidate_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TransactionDto> dco_decode_list_transaction_dto(dynamic raw);

  @protected
  List<TrustedDeviceDto> dco_decode_list_trusted_device_dto(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PairingCandidateDto dco_decode_pairing_candidate_dto(dynamic raw);

  @protected
  PairingKindDto dco_decode_pairing_kind_dto(dynamic raw);

  @protected
  PairingStateDto dco_decode_pairing_state_dto(dynamic raw);

  @protected
  PeerConnectionKindDto dco_decode_peer_connection_kind_dto(dynamic raw);

  @protected
  ProjectionDto dco_decode_projection_dto(dynamic raw);

  @protected
  ProjectionKindDto dco_decode_projection_kind_dto(dynamic raw);

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw);

  @protected
  TransactionDto dco_decode_transaction_dto(dynamic raw);

  @protected
  TransactionFilterDto dco_decode_transaction_filter_dto(dynamic raw);

  @protected
  TrustedDeviceDto dco_decode_trusted_device_dto(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  RustStreamSink<BootstrapDto> sse_decode_StreamSink_bootstrap_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeErrorEventDto>
  sse_decode_StreamSink_bridge_error_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DataChangedDto> sse_decode_StreamSink_data_changed_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<PairingCandidateDto>>
  sse_decode_StreamSink_list_pairing_candidate_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<TrustedDeviceDto>>
  sse_decode_StreamSink_list_trusted_device_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PairingStateDto> sse_decode_StreamSink_pairing_state_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProjectionDto> sse_decode_StreamSink_projection_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatusDto> sse_decode_StreamSink_sync_status_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AggregateDto sse_decode_aggregate_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BootstrapDto sse_decode_bootstrap_dto(SseDeserializer deserializer);

  @protected
  BootstrapKindDto sse_decode_bootstrap_kind_dto(SseDeserializer deserializer);

  @protected
  TransactionFilterDto sse_decode_box_autoadd_transaction_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorEventDto sse_decode_bridge_error_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer);

  @protected
  CategoryDto sse_decode_category_dto(SseDeserializer deserializer);

  @protected
  DataChangedDto sse_decode_data_changed_dto(SseDeserializer deserializer);

  @protected
  DomainKindDto sse_decode_domain_kind_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<CategoryDto> sse_decode_list_category_dto(SseDeserializer deserializer);

  @protected
  List<DomainKindDto> sse_decode_list_domain_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PairingCandidateDto> sse_decode_list_pairing_candidate_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TransactionDto> sse_decode_list_transaction_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TrustedDeviceDto> sse_decode_list_trusted_device_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PairingCandidateDto sse_decode_pairing_candidate_dto(
    SseDeserializer deserializer,
  );

  @protected
  PairingKindDto sse_decode_pairing_kind_dto(SseDeserializer deserializer);

  @protected
  PairingStateDto sse_decode_pairing_state_dto(SseDeserializer deserializer);

  @protected
  PeerConnectionKindDto sse_decode_peer_connection_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectionDto sse_decode_projection_dto(SseDeserializer deserializer);

  @protected
  ProjectionKindDto sse_decode_projection_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer);

  @protected
  TransactionDto sse_decode_transaction_dto(SseDeserializer deserializer);

  @protected
  TransactionFilterDto sse_decode_transaction_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  TrustedDeviceDto sse_decode_trusted_device_dto(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_bootstrap_dto_Sse(
    RustStreamSink<BootstrapDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_error_event_dto_Sse(
    RustStreamSink<BridgeErrorEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_data_changed_dto_Sse(
    RustStreamSink<DataChangedDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_pairing_candidate_dto_Sse(
    RustStreamSink<List<PairingCandidateDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_trusted_device_dto_Sse(
    RustStreamSink<List<TrustedDeviceDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_pairing_state_dto_Sse(
    RustStreamSink<PairingStateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_projection_dto_Sse(
    RustStreamSink<ProjectionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_dto_Sse(
    RustStreamSink<SyncStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aggregate_dto(AggregateDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_dto(BootstrapDto self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_kind_dto(
    BootstrapKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transaction_filter_dto(
    TransactionFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_event_dto(
    BridgeErrorEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_dto(CategoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_data_changed_dto(
    DataChangedDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_domain_kind_dto(DomainKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_category_dto(
    List<CategoryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_domain_kind_dto(
    List<DomainKindDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pairing_candidate_dto(
    List<PairingCandidateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_dto(
    List<TransactionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trusted_device_dto(
    List<TrustedDeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_candidate_dto(
    PairingCandidateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_kind_dto(
    PairingKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_state_dto(
    PairingStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_connection_kind_dto(
    PeerConnectionKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_projection_dto(ProjectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_projection_kind_dto(
    ProjectionKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_dto(SyncStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_dto(
    TransactionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_filter_dto(
    TransactionFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trusted_device_dto(
    TrustedDeviceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
