// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/collections.dart';
import 'api/lifecycle.dart';
import 'api/models.dart';
import 'api/pairing.dart';
import 'api/queries.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  RustStreamSink<BootstrapDto> dco_decode_StreamSink_bootstrap_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeErrorEventDto>
  dco_decode_StreamSink_bridge_error_event_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<DataChangedDto> dco_decode_StreamSink_data_changed_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<PairingCandidateDto>>
  dco_decode_StreamSink_list_pairing_candidate_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<List<TrustedDeviceDto>>
  dco_decode_StreamSink_list_trusted_device_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<PairingStateDto> dco_decode_StreamSink_pairing_state_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProjectionDto> dco_decode_StreamSink_projection_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncStatusDto> dco_decode_StreamSink_sync_status_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AggregationDto dco_decode_aggregation_dto(dynamic raw);

  @protected
  AggregationKindDto dco_decode_aggregation_kind_dto(dynamic raw);

  @protected
  ArithmeticOperatorDto dco_decode_arithmetic_operator_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BooleanOperatorDto dco_decode_boolean_operator_dto(dynamic raw);

  @protected
  BootstrapDto dco_decode_bootstrap_dto(dynamic raw);

  @protected
  BootstrapKindDto dco_decode_bootstrap_kind_dto(dynamic raw);

  @protected
  AggregationDto dco_decode_box_autoadd_aggregation_dto(dynamic raw);

  @protected
  ArithmeticOperatorDto dco_decode_box_autoadd_arithmetic_operator_dto(
    dynamic raw,
  );

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BooleanOperatorDto dco_decode_box_autoadd_boolean_operator_dto(dynamic raw);

  @protected
  CollectionQueryDto dco_decode_box_autoadd_collection_query_dto(dynamic raw);

  @protected
  CollectionSchemaDto dco_decode_box_autoadd_collection_schema_dto(dynamic raw);

  @protected
  ComparisonOperatorDto dco_decode_box_autoadd_comparison_operator_dto(
    dynamic raw,
  );

  @protected
  ComputedFieldDefinitionDto
  dco_decode_box_autoadd_computed_field_definition_dto(dynamic raw);

  @protected
  CurrentBoundaryDto dco_decode_box_autoadd_current_boundary_dto(dynamic raw);

  @protected
  EnumOptionDto dco_decode_box_autoadd_enum_option_dto(dynamic raw);

  @protected
  ExpressionDto dco_decode_box_autoadd_expression_dto(dynamic raw);

  @protected
  FieldDefinitionDto dco_decode_box_autoadd_field_definition_dto(dynamic raw);

  @protected
  FieldReferenceDto dco_decode_box_autoadd_field_reference_dto(dynamic raw);

  @protected
  FieldValueDto dco_decode_box_autoadd_field_value_dto(dynamic raw);

  @protected
  GroupingDto dco_decode_box_autoadd_grouping_dto(dynamic raw);

  @protected
  QueryDefinitionDto dco_decode_box_autoadd_query_definition_dto(dynamic raw);

  @protected
  RecordDto dco_decode_box_autoadd_record_dto(dynamic raw);

  @protected
  RoundingPolicyDto dco_decode_box_autoadd_rounding_policy_dto(dynamic raw);

  @protected
  TypedValueDto dco_decode_box_autoadd_typed_value_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  ValueTypeDto dco_decode_box_autoadd_value_type_dto(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorEventDto dco_decode_bridge_error_event_dto(dynamic raw);

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw);

  @protected
  BucketPeriodDto dco_decode_bucket_period_dto(dynamic raw);

  @protected
  CalendarPolicyDto dco_decode_calendar_policy_dto(dynamic raw);

  @protected
  CategoryPointDto dco_decode_category_point_dto(dynamic raw);

  @protected
  CollectionDto dco_decode_collection_dto(dynamic raw);

  @protected
  CollectionQueryDto dco_decode_collection_query_dto(dynamic raw);

  @protected
  CollectionSchemaDto dco_decode_collection_schema_dto(dynamic raw);

  @protected
  ComparisonOperatorDto dco_decode_comparison_operator_dto(dynamic raw);

  @protected
  ComputedFieldDefinitionDto dco_decode_computed_field_definition_dto(
    dynamic raw,
  );

  @protected
  CurrentBoundaryDto dco_decode_current_boundary_dto(dynamic raw);

  @protected
  DataChangedDto dco_decode_data_changed_dto(dynamic raw);

  @protected
  DiagnosticDto dco_decode_diagnostic_dto(dynamic raw);

  @protected
  DisplayMetadataDto dco_decode_display_metadata_dto(dynamic raw);

  @protected
  DomainKindDto dco_decode_domain_kind_dto(dynamic raw);

  @protected
  EnumOptionDto dco_decode_enum_option_dto(dynamic raw);

  @protected
  ExpressionDto dco_decode_expression_dto(dynamic raw);

  @protected
  ExpressionKindDto dco_decode_expression_kind_dto(dynamic raw);

  @protected
  ExpressionNodeDto dco_decode_expression_node_dto(dynamic raw);

  @protected
  FieldDefinitionDto dco_decode_field_definition_dto(dynamic raw);

  @protected
  FieldReferenceDto dco_decode_field_reference_dto(dynamic raw);

  @protected
  FieldReferenceKindDto dco_decode_field_reference_kind_dto(dynamic raw);

  @protected
  FieldTypeDto dco_decode_field_type_dto(dynamic raw);

  @protected
  FieldTypeKindDto dco_decode_field_type_kind_dto(dynamic raw);

  @protected
  FieldValueDto dco_decode_field_value_dto(dynamic raw);

  @protected
  FieldValueKindDto dco_decode_field_value_kind_dto(dynamic raw);

  @protected
  GroupingDto dco_decode_grouping_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CategoryPointDto> dco_decode_list_category_point_dto(dynamic raw);

  @protected
  List<CollectionDto> dco_decode_list_collection_dto(dynamic raw);

  @protected
  List<ComputedFieldDefinitionDto>
  dco_decode_list_computed_field_definition_dto(dynamic raw);

  @protected
  List<DiagnosticDto> dco_decode_list_diagnostic_dto(dynamic raw);

  @protected
  List<DomainKindDto> dco_decode_list_domain_kind_dto(dynamic raw);

  @protected
  List<EnumOptionDto> dco_decode_list_enum_option_dto(dynamic raw);

  @protected
  List<ExpressionNodeDto> dco_decode_list_expression_node_dto(dynamic raw);

  @protected
  List<FieldDefinitionDto> dco_decode_list_field_definition_dto(dynamic raw);

  @protected
  List<FieldReferenceDto> dco_decode_list_field_reference_dto(dynamic raw);

  @protected
  List<PairingCandidateDto> dco_decode_list_pairing_candidate_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QueryDefinitionDto> dco_decode_list_query_definition_dto(dynamic raw);

  @protected
  List<RecordDto> dco_decode_list_record_dto(dynamic raw);

  @protected
  List<RecordValueDto> dco_decode_list_record_value_dto(dynamic raw);

  @protected
  List<ResultRecordDto> dco_decode_list_result_record_dto(dynamic raw);

  @protected
  List<ResultRecordValueDto> dco_decode_list_result_record_value_dto(
    dynamic raw,
  );

  @protected
  List<SeriesPointDto> dco_decode_list_series_point_dto(dynamic raw);

  @protected
  List<SortClauseDto> dco_decode_list_sort_clause_dto(dynamic raw);

  @protected
  List<TrustedDeviceDto> dco_decode_list_trusted_device_dto(dynamic raw);

  @protected
  NullOrderDto dco_decode_null_order_dto(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AggregationDto? dco_decode_opt_box_autoadd_aggregation_dto(dynamic raw);

  @protected
  ArithmeticOperatorDto? dco_decode_opt_box_autoadd_arithmetic_operator_dto(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  BooleanOperatorDto? dco_decode_opt_box_autoadd_boolean_operator_dto(
    dynamic raw,
  );

  @protected
  CollectionQueryDto? dco_decode_opt_box_autoadd_collection_query_dto(
    dynamic raw,
  );

  @protected
  CollectionSchemaDto? dco_decode_opt_box_autoadd_collection_schema_dto(
    dynamic raw,
  );

  @protected
  ComparisonOperatorDto? dco_decode_opt_box_autoadd_comparison_operator_dto(
    dynamic raw,
  );

  @protected
  CurrentBoundaryDto? dco_decode_opt_box_autoadd_current_boundary_dto(
    dynamic raw,
  );

  @protected
  ExpressionDto? dco_decode_opt_box_autoadd_expression_dto(dynamic raw);

  @protected
  FieldReferenceDto? dco_decode_opt_box_autoadd_field_reference_dto(
    dynamic raw,
  );

  @protected
  FieldValueDto? dco_decode_opt_box_autoadd_field_value_dto(dynamic raw);

  @protected
  GroupingDto? dco_decode_opt_box_autoadd_grouping_dto(dynamic raw);

  @protected
  RecordDto? dco_decode_opt_box_autoadd_record_dto(dynamic raw);

  @protected
  RoundingPolicyDto? dco_decode_opt_box_autoadd_rounding_policy_dto(
    dynamic raw,
  );

  @protected
  TypedValueDto? dco_decode_opt_box_autoadd_typed_value_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  ValueTypeDto? dco_decode_opt_box_autoadd_value_type_dto(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PairingCandidateDto dco_decode_pairing_candidate_dto(dynamic raw);

  @protected
  PairingKindDto dco_decode_pairing_kind_dto(dynamic raw);

  @protected
  PairingStateDto dco_decode_pairing_state_dto(dynamic raw);

  @protected
  PeerConnectionKindDto dco_decode_peer_connection_kind_dto(dynamic raw);

  @protected
  ProjectionDto dco_decode_projection_dto(dynamic raw);

  @protected
  ProjectionKindDto dco_decode_projection_kind_dto(dynamic raw);

  @protected
  QueryDefinitionDto dco_decode_query_definition_dto(dynamic raw);

  @protected
  QueryResultDto dco_decode_query_result_dto(dynamic raw);

  @protected
  QueryResultKindDto dco_decode_query_result_kind_dto(dynamic raw);

  @protected
  QueryShapeDto dco_decode_query_shape_dto(dynamic raw);

  @protected
  QueryShapeKindDto dco_decode_query_shape_kind_dto(dynamic raw);

  @protected
  RecordDto dco_decode_record_dto(dynamic raw);

  @protected
  RecordValueDto dco_decode_record_value_dto(dynamic raw);

  @protected
  ResultRecordDto dco_decode_result_record_dto(dynamic raw);

  @protected
  ResultRecordValueDto dco_decode_result_record_value_dto(dynamic raw);

  @protected
  RoundingPolicyDto dco_decode_rounding_policy_dto(dynamic raw);

  @protected
  SeriesPointDto dco_decode_series_point_dto(dynamic raw);

  @protected
  SortClauseDto dco_decode_sort_clause_dto(dynamic raw);

  @protected
  SortDirectionDto dco_decode_sort_direction_dto(dynamic raw);

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw);

  @protected
  TrustedDeviceDto dco_decode_trusted_device_dto(dynamic raw);

  @protected
  TypedValueDto dco_decode_typed_value_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ValidationMetadataDto dco_decode_validation_metadata_dto(dynamic raw);

  @protected
  ValueTypeDto dco_decode_value_type_dto(dynamic raw);

  @protected
  ValueTypeKindDto dco_decode_value_type_kind_dto(dynamic raw);

  @protected
  WeekStartDto dco_decode_week_start_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  RustStreamSink<BootstrapDto> sse_decode_StreamSink_bootstrap_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeErrorEventDto>
  sse_decode_StreamSink_bridge_error_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DataChangedDto> sse_decode_StreamSink_data_changed_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<PairingCandidateDto>>
  sse_decode_StreamSink_list_pairing_candidate_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<TrustedDeviceDto>>
  sse_decode_StreamSink_list_trusted_device_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PairingStateDto> sse_decode_StreamSink_pairing_state_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProjectionDto> sse_decode_StreamSink_projection_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatusDto> sse_decode_StreamSink_sync_status_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AggregationDto sse_decode_aggregation_dto(SseDeserializer deserializer);

  @protected
  AggregationKindDto sse_decode_aggregation_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  ArithmeticOperatorDto sse_decode_arithmetic_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BooleanOperatorDto sse_decode_boolean_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  BootstrapDto sse_decode_bootstrap_dto(SseDeserializer deserializer);

  @protected
  BootstrapKindDto sse_decode_bootstrap_kind_dto(SseDeserializer deserializer);

  @protected
  AggregationDto sse_decode_box_autoadd_aggregation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ArithmeticOperatorDto sse_decode_box_autoadd_arithmetic_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BooleanOperatorDto sse_decode_box_autoadd_boolean_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  CollectionQueryDto sse_decode_box_autoadd_collection_query_dto(
    SseDeserializer deserializer,
  );

  @protected
  CollectionSchemaDto sse_decode_box_autoadd_collection_schema_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComparisonOperatorDto sse_decode_box_autoadd_comparison_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComputedFieldDefinitionDto
  sse_decode_box_autoadd_computed_field_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  CurrentBoundaryDto sse_decode_box_autoadd_current_boundary_dto(
    SseDeserializer deserializer,
  );

  @protected
  EnumOptionDto sse_decode_box_autoadd_enum_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExpressionDto sse_decode_box_autoadd_expression_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldDefinitionDto sse_decode_box_autoadd_field_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldReferenceDto sse_decode_box_autoadd_field_reference_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldValueDto sse_decode_box_autoadd_field_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupingDto sse_decode_box_autoadd_grouping_dto(SseDeserializer deserializer);

  @protected
  QueryDefinitionDto sse_decode_box_autoadd_query_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecordDto sse_decode_box_autoadd_record_dto(SseDeserializer deserializer);

  @protected
  RoundingPolicyDto sse_decode_box_autoadd_rounding_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  TypedValueDto sse_decode_box_autoadd_typed_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  ValueTypeDto sse_decode_box_autoadd_value_type_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorEventDto sse_decode_bridge_error_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer);

  @protected
  BucketPeriodDto sse_decode_bucket_period_dto(SseDeserializer deserializer);

  @protected
  CalendarPolicyDto sse_decode_calendar_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  CategoryPointDto sse_decode_category_point_dto(SseDeserializer deserializer);

  @protected
  CollectionDto sse_decode_collection_dto(SseDeserializer deserializer);

  @protected
  CollectionQueryDto sse_decode_collection_query_dto(
    SseDeserializer deserializer,
  );

  @protected
  CollectionSchemaDto sse_decode_collection_schema_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComparisonOperatorDto sse_decode_comparison_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComputedFieldDefinitionDto sse_decode_computed_field_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  CurrentBoundaryDto sse_decode_current_boundary_dto(
    SseDeserializer deserializer,
  );

  @protected
  DataChangedDto sse_decode_data_changed_dto(SseDeserializer deserializer);

  @protected
  DiagnosticDto sse_decode_diagnostic_dto(SseDeserializer deserializer);

  @protected
  DisplayMetadataDto sse_decode_display_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  DomainKindDto sse_decode_domain_kind_dto(SseDeserializer deserializer);

  @protected
  EnumOptionDto sse_decode_enum_option_dto(SseDeserializer deserializer);

  @protected
  ExpressionDto sse_decode_expression_dto(SseDeserializer deserializer);

  @protected
  ExpressionKindDto sse_decode_expression_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExpressionNodeDto sse_decode_expression_node_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldDefinitionDto sse_decode_field_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldReferenceDto sse_decode_field_reference_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldReferenceKindDto sse_decode_field_reference_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldTypeDto sse_decode_field_type_dto(SseDeserializer deserializer);

  @protected
  FieldTypeKindDto sse_decode_field_type_kind_dto(SseDeserializer deserializer);

  @protected
  FieldValueDto sse_decode_field_value_dto(SseDeserializer deserializer);

  @protected
  FieldValueKindDto sse_decode_field_value_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupingDto sse_decode_grouping_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CategoryPointDto> sse_decode_list_category_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CollectionDto> sse_decode_list_collection_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ComputedFieldDefinitionDto>
  sse_decode_list_computed_field_definition_dto(SseDeserializer deserializer);

  @protected
  List<DiagnosticDto> sse_decode_list_diagnostic_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DomainKindDto> sse_decode_list_domain_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EnumOptionDto> sse_decode_list_enum_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ExpressionNodeDto> sse_decode_list_expression_node_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldDefinitionDto> sse_decode_list_field_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldReferenceDto> sse_decode_list_field_reference_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PairingCandidateDto> sse_decode_list_pairing_candidate_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QueryDefinitionDto> sse_decode_list_query_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RecordDto> sse_decode_list_record_dto(SseDeserializer deserializer);

  @protected
  List<RecordValueDto> sse_decode_list_record_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ResultRecordDto> sse_decode_list_result_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ResultRecordValueDto> sse_decode_list_result_record_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SeriesPointDto> sse_decode_list_series_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SortClauseDto> sse_decode_list_sort_clause_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TrustedDeviceDto> sse_decode_list_trusted_device_dto(
    SseDeserializer deserializer,
  );

  @protected
  NullOrderDto sse_decode_null_order_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AggregationDto? sse_decode_opt_box_autoadd_aggregation_dto(
    SseDeserializer deserializer,
  );

  @protected
  ArithmeticOperatorDto? sse_decode_opt_box_autoadd_arithmetic_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BooleanOperatorDto? sse_decode_opt_box_autoadd_boolean_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  CollectionQueryDto? sse_decode_opt_box_autoadd_collection_query_dto(
    SseDeserializer deserializer,
  );

  @protected
  CollectionSchemaDto? sse_decode_opt_box_autoadd_collection_schema_dto(
    SseDeserializer deserializer,
  );

  @protected
  ComparisonOperatorDto? sse_decode_opt_box_autoadd_comparison_operator_dto(
    SseDeserializer deserializer,
  );

  @protected
  CurrentBoundaryDto? sse_decode_opt_box_autoadd_current_boundary_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExpressionDto? sse_decode_opt_box_autoadd_expression_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldReferenceDto? sse_decode_opt_box_autoadd_field_reference_dto(
    SseDeserializer deserializer,
  );

  @protected
  FieldValueDto? sse_decode_opt_box_autoadd_field_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  GroupingDto? sse_decode_opt_box_autoadd_grouping_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecordDto? sse_decode_opt_box_autoadd_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoundingPolicyDto? sse_decode_opt_box_autoadd_rounding_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  TypedValueDto? sse_decode_opt_box_autoadd_typed_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  ValueTypeDto? sse_decode_opt_box_autoadd_value_type_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PairingCandidateDto sse_decode_pairing_candidate_dto(
    SseDeserializer deserializer,
  );

  @protected
  PairingKindDto sse_decode_pairing_kind_dto(SseDeserializer deserializer);

  @protected
  PairingStateDto sse_decode_pairing_state_dto(SseDeserializer deserializer);

  @protected
  PeerConnectionKindDto sse_decode_peer_connection_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectionDto sse_decode_projection_dto(SseDeserializer deserializer);

  @protected
  ProjectionKindDto sse_decode_projection_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  QueryDefinitionDto sse_decode_query_definition_dto(
    SseDeserializer deserializer,
  );

  @protected
  QueryResultDto sse_decode_query_result_dto(SseDeserializer deserializer);

  @protected
  QueryResultKindDto sse_decode_query_result_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  QueryShapeDto sse_decode_query_shape_dto(SseDeserializer deserializer);

  @protected
  QueryShapeKindDto sse_decode_query_shape_kind_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecordDto sse_decode_record_dto(SseDeserializer deserializer);

  @protected
  RecordValueDto sse_decode_record_value_dto(SseDeserializer deserializer);

  @protected
  ResultRecordDto sse_decode_result_record_dto(SseDeserializer deserializer);

  @protected
  ResultRecordValueDto sse_decode_result_record_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  RoundingPolicyDto sse_decode_rounding_policy_dto(
    SseDeserializer deserializer,
  );

  @protected
  SeriesPointDto sse_decode_series_point_dto(SseDeserializer deserializer);

  @protected
  SortClauseDto sse_decode_sort_clause_dto(SseDeserializer deserializer);

  @protected
  SortDirectionDto sse_decode_sort_direction_dto(SseDeserializer deserializer);

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer);

  @protected
  TrustedDeviceDto sse_decode_trusted_device_dto(SseDeserializer deserializer);

  @protected
  TypedValueDto sse_decode_typed_value_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ValidationMetadataDto sse_decode_validation_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  ValueTypeDto sse_decode_value_type_dto(SseDeserializer deserializer);

  @protected
  ValueTypeKindDto sse_decode_value_type_kind_dto(SseDeserializer deserializer);

  @protected
  WeekStartDto sse_decode_week_start_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_bootstrap_dto_Sse(
    RustStreamSink<BootstrapDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_error_event_dto_Sse(
    RustStreamSink<BridgeErrorEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_data_changed_dto_Sse(
    RustStreamSink<DataChangedDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_pairing_candidate_dto_Sse(
    RustStreamSink<List<PairingCandidateDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_trusted_device_dto_Sse(
    RustStreamSink<List<TrustedDeviceDto>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_pairing_state_dto_Sse(
    RustStreamSink<PairingStateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_projection_dto_Sse(
    RustStreamSink<ProjectionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_dto_Sse(
    RustStreamSink<SyncStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aggregation_dto(
    AggregationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_aggregation_kind_dto(
    AggregationKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_arithmetic_operator_dto(
    ArithmeticOperatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_boolean_operator_dto(
    BooleanOperatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bootstrap_dto(BootstrapDto self, SseSerializer serializer);

  @protected
  void sse_encode_bootstrap_kind_dto(
    BootstrapKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_aggregation_dto(
    AggregationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_arithmetic_operator_dto(
    ArithmeticOperatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_boolean_operator_dto(
    BooleanOperatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_collection_query_dto(
    CollectionQueryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_collection_schema_dto(
    CollectionSchemaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_comparison_operator_dto(
    ComparisonOperatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_computed_field_definition_dto(
    ComputedFieldDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_current_boundary_dto(
    CurrentBoundaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_enum_option_dto(
    EnumOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_expression_dto(
    ExpressionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_field_definition_dto(
    FieldDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_field_reference_dto(
    FieldReferenceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_field_value_dto(
    FieldValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_grouping_dto(
    GroupingDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_query_definition_dto(
    QueryDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_dto(
    RecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rounding_policy_dto(
    RoundingPolicyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_typed_value_dto(
    TypedValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_value_type_dto(
    ValueTypeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_event_dto(
    BridgeErrorEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bucket_period_dto(
    BucketPeriodDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_policy_dto(
    CalendarPolicyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category_point_dto(
    CategoryPointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_collection_dto(CollectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_collection_query_dto(
    CollectionQueryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_collection_schema_dto(
    CollectionSchemaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comparison_operator_dto(
    ComparisonOperatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_computed_field_definition_dto(
    ComputedFieldDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_current_boundary_dto(
    CurrentBoundaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_data_changed_dto(
    DataChangedDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diagnostic_dto(DiagnosticDto self, SseSerializer serializer);

  @protected
  void sse_encode_display_metadata_dto(
    DisplayMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_domain_kind_dto(DomainKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_enum_option_dto(EnumOptionDto self, SseSerializer serializer);

  @protected
  void sse_encode_expression_dto(ExpressionDto self, SseSerializer serializer);

  @protected
  void sse_encode_expression_kind_dto(
    ExpressionKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_expression_node_dto(
    ExpressionNodeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_definition_dto(
    FieldDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_reference_dto(
    FieldReferenceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_reference_kind_dto(
    FieldReferenceKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_type_dto(FieldTypeDto self, SseSerializer serializer);

  @protected
  void sse_encode_field_type_kind_dto(
    FieldTypeKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_field_value_dto(FieldValueDto self, SseSerializer serializer);

  @protected
  void sse_encode_field_value_kind_dto(
    FieldValueKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_grouping_dto(GroupingDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category_point_dto(
    List<CategoryPointDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_collection_dto(
    List<CollectionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_computed_field_definition_dto(
    List<ComputedFieldDefinitionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diagnostic_dto(
    List<DiagnosticDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_domain_kind_dto(
    List<DomainKindDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_enum_option_dto(
    List<EnumOptionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_expression_node_dto(
    List<ExpressionNodeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_definition_dto(
    List<FieldDefinitionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_reference_dto(
    List<FieldReferenceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pairing_candidate_dto(
    List<PairingCandidateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_query_definition_dto(
    List<QueryDefinitionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_dto(
    List<RecordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_value_dto(
    List<RecordValueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_result_record_dto(
    List<ResultRecordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_result_record_value_dto(
    List<ResultRecordValueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_series_point_dto(
    List<SeriesPointDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sort_clause_dto(
    List<SortClauseDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trusted_device_dto(
    List<TrustedDeviceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_null_order_dto(NullOrderDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_aggregation_dto(
    AggregationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_arithmetic_operator_dto(
    ArithmeticOperatorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_boolean_operator_dto(
    BooleanOperatorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_collection_query_dto(
    CollectionQueryDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_collection_schema_dto(
    CollectionSchemaDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_comparison_operator_dto(
    ComparisonOperatorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_current_boundary_dto(
    CurrentBoundaryDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_expression_dto(
    ExpressionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_field_reference_dto(
    FieldReferenceDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_field_value_dto(
    FieldValueDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_grouping_dto(
    GroupingDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_dto(
    RecordDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rounding_policy_dto(
    RoundingPolicyDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_typed_value_dto(
    TypedValueDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_value_type_dto(
    ValueTypeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_candidate_dto(
    PairingCandidateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_kind_dto(
    PairingKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_state_dto(
    PairingStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_connection_kind_dto(
    PeerConnectionKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_projection_dto(ProjectionDto self, SseSerializer serializer);

  @protected
  void sse_encode_projection_kind_dto(
    ProjectionKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_query_definition_dto(
    QueryDefinitionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_query_result_dto(
    QueryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_query_result_kind_dto(
    QueryResultKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_query_shape_dto(QueryShapeDto self, SseSerializer serializer);

  @protected
  void sse_encode_query_shape_kind_dto(
    QueryShapeKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_dto(RecordDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_value_dto(
    RecordValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_result_record_dto(
    ResultRecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_result_record_value_dto(
    ResultRecordValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rounding_policy_dto(
    RoundingPolicyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_series_point_dto(
    SeriesPointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sort_clause_dto(SortClauseDto self, SseSerializer serializer);

  @protected
  void sse_encode_sort_direction_dto(
    SortDirectionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_dto(SyncStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_trusted_device_dto(
    TrustedDeviceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_typed_value_dto(TypedValueDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_validation_metadata_dto(
    ValidationMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_value_type_dto(ValueTypeDto self, SseSerializer serializer);

  @protected
  void sse_encode_value_type_kind_dto(
    ValueTypeKindDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_week_start_dto(WeekStartDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
