// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/finance.dart';
import 'api/lifecycle.dart';
import 'api/models.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiLifecycleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 95694160;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'app_bridge',
        ioDirectory: '../crates/app_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AggregateDto> crateApiModelsAggregateDtoDefault();

  Future<AggregateDto> crateApiFinanceAggregates();

  Future<BootstrapDto> crateApiLifecycleBootstrapState();

  Stream<BootstrapDto> crateApiLifecycleBootstrapStream();

  Future<String> crateApiFinanceCreateCategory({required String name});

  Future<BootstrapDto> crateApiFinanceCreateNewDataset();

  Future<String> crateApiFinanceCreateTransaction({
    required int occurredAtMs,
    required String categoryId,
    required int amountMinor,
    required String description,
  });

  Stream<DataChangedDto> crateApiLifecycleDataChangedStream();

  Future<void> crateApiFinanceDeleteCategory({required String id});

  Future<void> crateApiFinanceDeleteTransaction({required String id});

  Stream<BridgeErrorEventDto> crateApiLifecycleErrorStream();

  Future<void> crateApiLifecycleInitApp();

  Future<BootstrapDto> crateApiLifecycleInitialize({required String dataDir});

  Future<List<CategoryDto>> crateApiFinanceListCategories();

  Future<List<TransactionDto>> crateApiFinanceListTransactions({
    required TransactionFilterDto filter,
  });

  Future<ProjectionDto> crateApiLifecycleProjectionState();

  Stream<ProjectionDto> crateApiLifecycleProjectionStream();

  Future<void> crateApiLifecycleShutdown();

  Future<TransactionFilterDto> crateApiModelsTransactionFilterDtoDefault();

  Future<void> crateApiFinanceUpdateCategory({
    required String id,
    required String name,
  });

  Future<void> crateApiFinanceUpdateTransaction({
    required String id,
    int? occurredAtMs,
    String? categoryId,
    int? amountMinor,
    String? description,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AggregateDto> crateApiModelsAggregateDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_aggregate_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsAggregateDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsAggregateDtoDefaultConstMeta =>
      const TaskConstMeta(debugName: "aggregate_dto_default", argNames: []);

  @override
  Future<AggregateDto> crateApiFinanceAggregates() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_aggregate_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceAggregatesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceAggregatesConstMeta =>
      const TaskConstMeta(debugName: "aggregates", argNames: []);

  @override
  Future<BootstrapDto> crateApiLifecycleBootstrapState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bootstrap_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiLifecycleBootstrapStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleBootstrapStateConstMeta =>
      const TaskConstMeta(debugName: "bootstrap_state", argNames: []);

  @override
  Stream<BootstrapDto> crateApiLifecycleBootstrapStream() {
    final sink = RustStreamSink<BootstrapDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_bootstrap_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_bridge_error,
          ),
          constMeta: kCrateApiLifecycleBootstrapStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLifecycleBootstrapStreamConstMeta =>
      const TaskConstMeta(debugName: "bootstrap_stream", argNames: ["sink"]);

  @override
  Future<String> crateApiFinanceCreateCategory({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceCreateCategoryConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceCreateCategoryConstMeta =>
      const TaskConstMeta(debugName: "create_category", argNames: ["name"]);

  @override
  Future<BootstrapDto> crateApiFinanceCreateNewDataset() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bootstrap_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceCreateNewDatasetConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceCreateNewDatasetConstMeta =>
      const TaskConstMeta(debugName: "create_new_dataset", argNames: []);

  @override
  Future<String> crateApiFinanceCreateTransaction({
    required int occurredAtMs,
    required String categoryId,
    required int amountMinor,
    required String description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_i_64(occurredAtMs, serializer);
          sse_encode_String(categoryId, serializer);
          sse_encode_CastedPrimitive_i_64(amountMinor, serializer);
          sse_encode_String(description, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceCreateTransactionConstMeta,
        argValues: [occurredAtMs, categoryId, amountMinor, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceCreateTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "create_transaction",
        argNames: ["occurredAtMs", "categoryId", "amountMinor", "description"],
      );

  @override
  Stream<DataChangedDto> crateApiLifecycleDataChangedStream() {
    final sink = RustStreamSink<DataChangedDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_data_changed_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_bridge_error,
          ),
          constMeta: kCrateApiLifecycleDataChangedStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLifecycleDataChangedStreamConstMeta =>
      const TaskConstMeta(debugName: "data_changed_stream", argNames: ["sink"]);

  @override
  Future<void> crateApiFinanceDeleteCategory({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceDeleteCategoryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceDeleteCategoryConstMeta =>
      const TaskConstMeta(debugName: "delete_category", argNames: ["id"]);

  @override
  Future<void> crateApiFinanceDeleteTransaction({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceDeleteTransactionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceDeleteTransactionConstMeta =>
      const TaskConstMeta(debugName: "delete_transaction", argNames: ["id"]);

  @override
  Stream<BridgeErrorEventDto> crateApiLifecycleErrorStream() {
    final sink = RustStreamSink<BridgeErrorEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_bridge_error_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_bridge_error,
          ),
          constMeta: kCrateApiLifecycleErrorStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLifecycleErrorStreamConstMeta =>
      const TaskConstMeta(debugName: "error_stream", argNames: ["sink"]);

  @override
  Future<void> crateApiLifecycleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLifecycleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<BootstrapDto> crateApiLifecycleInitialize({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bootstrap_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiLifecycleInitializeConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleInitializeConstMeta =>
      const TaskConstMeta(debugName: "initialize", argNames: ["dataDir"]);

  @override
  Future<List<CategoryDto>> crateApiFinanceListCategories() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_category_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceListCategoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceListCategoriesConstMeta =>
      const TaskConstMeta(debugName: "list_categories", argNames: []);

  @override
  Future<List<TransactionDto>> crateApiFinanceListTransactions({
    required TransactionFilterDto filter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_transaction_filter_dto(filter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_transaction_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceListTransactionsConstMeta,
        argValues: [filter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceListTransactionsConstMeta =>
      const TaskConstMeta(debugName: "list_transactions", argNames: ["filter"]);

  @override
  Future<ProjectionDto> crateApiLifecycleProjectionState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_projection_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiLifecycleProjectionStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleProjectionStateConstMeta =>
      const TaskConstMeta(debugName: "projection_state", argNames: []);

  @override
  Stream<ProjectionDto> crateApiLifecycleProjectionStream() {
    final sink = RustStreamSink<ProjectionDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_projection_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_bridge_error,
          ),
          constMeta: kCrateApiLifecycleProjectionStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLifecycleProjectionStreamConstMeta =>
      const TaskConstMeta(debugName: "projection_stream", argNames: ["sink"]);

  @override
  Future<void> crateApiLifecycleShutdown() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiLifecycleShutdownConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleShutdownConstMeta =>
      const TaskConstMeta(debugName: "shutdown", argNames: []);

  @override
  Future<TransactionFilterDto> crateApiModelsTransactionFilterDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transaction_filter_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsTransactionFilterDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsTransactionFilterDtoDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "transaction_filter_dto_default",
        argNames: [],
      );

  @override
  Future<void> crateApiFinanceUpdateCategory({
    required String id,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceUpdateCategoryConstMeta,
        argValues: [id, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceUpdateCategoryConstMeta =>
      const TaskConstMeta(
        debugName: "update_category",
        argNames: ["id", "name"],
      );

  @override
  Future<void> crateApiFinanceUpdateTransaction({
    required String id,
    int? occurredAtMs,
    String? categoryId,
    int? amountMinor,
    String? description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_opt_CastedPrimitive_i_64(occurredAtMs, serializer);
          sse_encode_opt_String(categoryId, serializer);
          sse_encode_opt_CastedPrimitive_i_64(amountMinor, serializer);
          sse_encode_opt_String(description, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFinanceUpdateTransactionConstMeta,
        argValues: [id, occurredAtMs, categoryId, amountMinor, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFinanceUpdateTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "update_transaction",
        argNames: [
          "id",
          "occurredAtMs",
          "categoryId",
          "amountMinor",
          "description",
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  RustStreamSink<BootstrapDto> dco_decode_StreamSink_bootstrap_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<BridgeErrorEventDto>
  dco_decode_StreamSink_bridge_error_event_dto_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<DataChangedDto> dco_decode_StreamSink_data_changed_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ProjectionDto> dco_decode_StreamSink_projection_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AggregateDto dco_decode_aggregate_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AggregateDto(
      balanceMinor: dco_decode_CastedPrimitive_i_64(arr[0]),
      incomeMinor: dco_decode_CastedPrimitive_i_64(arr[1]),
      expenseMinor: dco_decode_CastedPrimitive_i_64(arr[2]),
      transactionCount: dco_decode_CastedPrimitive_i_64(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BootstrapDto dco_decode_bootstrap_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BootstrapDto(
      kind: dco_decode_bootstrap_kind_dto(arr[0]),
      rootId: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  BootstrapKindDto dco_decode_bootstrap_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BootstrapKindDto.values[raw as int];
  }

  @protected
  TransactionFilterDto dco_decode_box_autoadd_transaction_filter_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transaction_filter_dto(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeError(
      kind: dco_decode_bridge_error_kind(arr[0]),
      field: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeErrorEventDto dco_decode_bridge_error_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeErrorEventDto(
      kind: dco_decode_bridge_error_kind(arr[0]),
      operation: dco_decode_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeErrorKind dco_decode_bridge_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorKind.values[raw as int];
  }

  @protected
  CategoryDto dco_decode_category_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CategoryDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  DataChangedDto dco_decode_data_changed_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DataChangedDto(
      kinds: dco_decode_list_domain_kind_dto(arr[0]),
      checkpoint: dco_decode_String(arr[1]),
    );
  }

  @protected
  DomainKindDto dco_decode_domain_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DomainKindDto.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<CategoryDto> dco_decode_list_category_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_category_dto).toList();
  }

  @protected
  List<DomainKindDto> dco_decode_list_domain_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_domain_kind_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TransactionDto> dco_decode_list_transaction_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transaction_dto).toList();
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_i_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ProjectionDto dco_decode_projection_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProjectionDto(
      kind: dco_decode_projection_kind_dto(arr[0]),
      checkpoint: dco_decode_opt_String(arr[1]),
      message: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ProjectionKindDto dco_decode_projection_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProjectionKindDto.values[raw as int];
  }

  @protected
  TransactionDto dco_decode_transaction_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TransactionDto(
      id: dco_decode_String(arr[0]),
      occurredAtMs: dco_decode_CastedPrimitive_i_64(arr[1]),
      categoryId: dco_decode_String(arr[2]),
      categoryName: dco_decode_opt_String(arr[3]),
      categoryAvailable: dco_decode_bool(arr[4]),
      amountMinor: dco_decode_CastedPrimitive_i_64(arr[5]),
      description: dco_decode_String(arr[6]),
    );
  }

  @protected
  TransactionFilterDto dco_decode_transaction_filter_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TransactionFilterDto(
      text: dco_decode_opt_String(arr[0]),
      categoryId: dco_decode_opt_String(arr[1]),
      fromMs: dco_decode_opt_CastedPrimitive_i_64(arr[2]),
      throughMs: dco_decode_opt_CastedPrimitive_i_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  RustStreamSink<BootstrapDto> sse_decode_StreamSink_bootstrap_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<BridgeErrorEventDto>
  sse_decode_StreamSink_bridge_error_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<DataChangedDto> sse_decode_StreamSink_data_changed_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ProjectionDto> sse_decode_StreamSink_projection_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AggregateDto sse_decode_aggregate_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_balanceMinor = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_incomeMinor = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_expenseMinor = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_transactionCount = sse_decode_CastedPrimitive_i_64(deserializer);
    return AggregateDto(
      balanceMinor: var_balanceMinor,
      incomeMinor: var_incomeMinor,
      expenseMinor: var_expenseMinor,
      transactionCount: var_transactionCount,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BootstrapDto sse_decode_bootstrap_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_bootstrap_kind_dto(deserializer);
    var var_rootId = sse_decode_opt_String(deserializer);
    return BootstrapDto(kind: var_kind, rootId: var_rootId);
  }

  @protected
  BootstrapKindDto sse_decode_bootstrap_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BootstrapKindDto.values[inner];
  }

  @protected
  TransactionFilterDto sse_decode_box_autoadd_transaction_filter_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transaction_filter_dto(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_bridge_error_kind(deserializer);
    var var_field = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeError(kind: var_kind, field: var_field, message: var_message);
  }

  @protected
  BridgeErrorEventDto sse_decode_bridge_error_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_bridge_error_kind(deserializer);
    var var_operation = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeErrorEventDto(
      kind: var_kind,
      operation: var_operation,
      message: var_message,
    );
  }

  @protected
  BridgeErrorKind sse_decode_bridge_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeErrorKind.values[inner];
  }

  @protected
  CategoryDto sse_decode_category_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return CategoryDto(id: var_id, name: var_name);
  }

  @protected
  DataChangedDto sse_decode_data_changed_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kinds = sse_decode_list_domain_kind_dto(deserializer);
    var var_checkpoint = sse_decode_String(deserializer);
    return DataChangedDto(kinds: var_kinds, checkpoint: var_checkpoint);
  }

  @protected
  DomainKindDto sse_decode_domain_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DomainKindDto.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<CategoryDto> sse_decode_list_category_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CategoryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_category_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DomainKindDto> sse_decode_list_domain_kind_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DomainKindDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_domain_kind_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TransactionDto> sse_decode_list_transaction_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransactionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transaction_dto(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectionDto sse_decode_projection_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_projection_kind_dto(deserializer);
    var var_checkpoint = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return ProjectionDto(
      kind: var_kind,
      checkpoint: var_checkpoint,
      message: var_message,
    );
  }

  @protected
  ProjectionKindDto sse_decode_projection_kind_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProjectionKindDto.values[inner];
  }

  @protected
  TransactionDto sse_decode_transaction_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_occurredAtMs = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_categoryId = sse_decode_String(deserializer);
    var var_categoryName = sse_decode_opt_String(deserializer);
    var var_categoryAvailable = sse_decode_bool(deserializer);
    var var_amountMinor = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_description = sse_decode_String(deserializer);
    return TransactionDto(
      id: var_id,
      occurredAtMs: var_occurredAtMs,
      categoryId: var_categoryId,
      categoryName: var_categoryName,
      categoryAvailable: var_categoryAvailable,
      amountMinor: var_amountMinor,
      description: var_description,
    );
  }

  @protected
  TransactionFilterDto sse_decode_transaction_filter_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_opt_String(deserializer);
    var var_categoryId = sse_decode_opt_String(deserializer);
    var var_fromMs = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    var var_throughMs = sse_decode_opt_CastedPrimitive_i_64(deserializer);
    return TransactionFilterDto(
      text: var_text,
      categoryId: var_categoryId,
      fromMs: var_fromMs,
      throughMs: var_throughMs,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_StreamSink_bootstrap_dto_Sse(
    RustStreamSink<BootstrapDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bootstrap_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_bridge_error_event_dto_Sse(
    RustStreamSink<BridgeErrorEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_error_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_data_changed_dto_Sse(
    RustStreamSink<DataChangedDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_data_changed_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_projection_dto_Sse(
    RustStreamSink<ProjectionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_projection_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_aggregate_dto(AggregateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_i_64(self.balanceMinor, serializer);
    sse_encode_CastedPrimitive_i_64(self.incomeMinor, serializer);
    sse_encode_CastedPrimitive_i_64(self.expenseMinor, serializer);
    sse_encode_CastedPrimitive_i_64(self.transactionCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bootstrap_dto(BootstrapDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bootstrap_kind_dto(self.kind, serializer);
    sse_encode_opt_String(self.rootId, serializer);
  }

  @protected
  void sse_encode_bootstrap_kind_dto(
    BootstrapKindDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transaction_filter_dto(
    TransactionFilterDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transaction_filter_dto(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error_kind(self.kind, serializer);
    sse_encode_opt_String(self.field, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bridge_error_event_dto(
    BridgeErrorEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error_kind(self.kind, serializer);
    sse_encode_String(self.operation, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bridge_error_kind(
    BridgeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_category_dto(CategoryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_data_changed_dto(
    DataChangedDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_domain_kind_dto(self.kinds, serializer);
    sse_encode_String(self.checkpoint, serializer);
  }

  @protected
  void sse_encode_domain_kind_dto(
    DomainKindDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_category_dto(
    List<CategoryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_category_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_domain_kind_dto(
    List<DomainKindDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_domain_kind_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transaction_dto(
    List<TransactionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transaction_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_CastedPrimitive_i_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_projection_dto(ProjectionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_projection_kind_dto(self.kind, serializer);
    sse_encode_opt_String(self.checkpoint, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_projection_kind_dto(
    ProjectionKindDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transaction_dto(
    TransactionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_CastedPrimitive_i_64(self.occurredAtMs, serializer);
    sse_encode_String(self.categoryId, serializer);
    sse_encode_opt_String(self.categoryName, serializer);
    sse_encode_bool(self.categoryAvailable, serializer);
    sse_encode_CastedPrimitive_i_64(self.amountMinor, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_transaction_filter_dto(
    TransactionFilterDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.categoryId, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.fromMs, serializer);
    sse_encode_opt_CastedPrimitive_i_64(self.throughMs, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
